export const TEMPLATES = {
  arte: {
    post: [
      "Descubra como [tema] transforma sua criatividade 🎨 #arte #criatividade #inspiracao",
      "Dicas para pintar [tema] de forma incrível 🖌️ #arte #pintura #tutorial",
      "Como [tema] inspira novos estilos artísticos 🎨 #arte #inspiracao #design",
      "Antes e depois: veja como [tema] muda suas obras 🖌️ #arte #antesedepois #criatividade",
      "Aprenda técnicas de [tema] passo a passo 🎨 #arte #tecnica #tutorial",
      "Como [tema] ajuda a desenvolver habilidades artísticas 🖌️ #arte #habilidades #criatividade",
      "Top 5 ideias para usar [tema] em suas pinturas 🎨 #arte #dicas #inspiracao",
      "Transforme [tema] em uma obra-prima 🖌️ #arte #criatividade #design",
      "Como [tema] influencia tendências artísticas 🎨 #arte #tendencias #inspiracao",
      "Dicas de materiais para trabalhar com [tema] 🖌️ #arte #materiais #pintura",
      "Como [tema] pode ser interpretado de forma moderna 🎨 #arte #moderno #criatividade",
      "Exemplos incríveis de [tema] que você precisa conhecer 🖌️ #arte #exemplos #inspiracao",
      "Como [tema] ajuda a desenvolver expressão pessoal 🎨 #arte #expressao #criatividade",
      "Passo a passo para criar [tema] de maneira profissional 🖌️ #arte #tutorial #passoapasso",
      "Como [tema] transforma simples rabiscos em arte 🎨 #arte #criatividade #design",
      "Dicas de iluminação para destacar [tema] 🖌️ #arte #iluminacao #fotografia",
      "Como [tema] pode ser usado em murais e paredes 🎨 #arte #mural #decoracao",
      "Top 10 ideias de composição com [tema] 🖌️ #arte #composicao #design",
      "Como [tema] inspira novos projetos artísticos 🎨 #arte #projeto #criatividade",
      "Dicas de cores para trabalhar com [tema] 🖌️ #arte #cores #pintura",
      "Como [tema] se conecta com arte digital 🎨 #arte #digital #criatividade",
      "Técnicas avançadas para aperfeiçoar [tema] 🖌️ #arte #avancado #tutorial",
      "Como [tema] pode ser interpretado em diferentes estilos 🎨 #arte #estilo #criatividade",
      "Inspiração diária: use [tema] para criar novas obras 🖌️ #arte #inspiracao #diario",
      "Como [tema] transforma sua perspectiva artística 🎨 #arte #perspectiva #criatividade",
      "Dicas de desenho para ilustrar [tema] 🖌️ #arte #desenho #tutorial",
      "Como [tema] influencia a arte contemporânea 🎨 #arte #contemporanea #inspiracao",
      "Top 5 erros comuns ao trabalhar com [tema] 🖌️ #arte #erros #dicas",
      "Como [tema] pode ser aplicado em esculturas 🎨 #arte #escultura #criatividade",
      "Dicas de combinação de técnicas com [tema] 🖌️ #arte #tecnicas #design",
      "Como [tema] inspira ilustrações digitais 🎨 #arte #digital #inspiracao",
      "Ideias criativas para usar [tema] em sketchbooks 🖌️ #arte #sketchbook #criatividade",
      "Como [tema] transforma simples rabiscos em grandes obras 🎨 #arte #desenho #criatividade",
      "Dicas de pintura em aquarela para [tema] 🖌️ #arte #aquarela #tutorial",
      "Como [tema] se conecta com fotografia artística 🎨 #arte #fotografia #inspiracao",
      "Top 5 formas de interpretar [tema] em arte moderna 🖌️ #arte #moderno #criatividade",
      "Como [tema] ajuda a desenvolver observação e atenção 🎨 #arte #detalhes #criatividade",
      "Dicas de materiais sustentáveis para criar [tema] 🖌️ #arte #sustentavel #materiais",
      "Como [tema] pode ser incorporado em design gráfico 🎨 #arte #designgrafico #criatividade",
      "Passo a passo de técnicas mistas com [tema] 🖌️ #arte #tecnicas #tutorial",
      "Como [tema] inspira novas paletas de cores 🎨 #arte #cores #criatividade",
      "Ideias para exposições usando [tema] 🖌️ #arte #exposicao #inspiracao",
      "Como [tema] pode ser usado em ilustrações de livros 🎨 #arte #livros #criatividade",
      "Top 5 inspirações clássicas com [tema] 🖌️ #arte #classico #inspiracao",
      "Como [tema] ajuda a desenvolver técnicas de sombreamento 🎨 #arte #sombreamento #tutorial",
      "Dicas para capturar [tema] em pinturas digitais 🖌️ #arte #digital #pintura",
      "Como [tema] transforma simples desenhos em storytelling 🎨 #arte #historia #criatividade",
      "Passo a passo para criar [tema] em acrílico 🖌️ #arte #acrilico #tutorial",
      "Como [tema] inspira murais colaborativos 🎨 #arte #colaborativo #criatividade",
      "Top 10 artistas que trabalham com [tema] 🖌️ #arte #inspiracao #referencias",
      "Como [tema] pode ser usado em lettering e tipografia 🎨 #arte #lettering #criatividade",
      "Dicas de iluminação e fotografia para destacar [tema] 🖌️ #arte #fotografia #tutorial",
      "Como [tema] transforma suas ideias em conceito visual 🎨 #arte #conceito #criatividade",
      "Top 5 técnicas para dar vida a [tema] 🖌️ #arte #tecnicas #tutorial",
      "Como [tema] influencia estilos artísticos ao redor do mundo 🎨 #arte #estilo #criatividade",
      "Dicas para usar [tema] em colagens e mixed media 🖌️ #arte #collage #criatividade",
      "Como [tema] ajuda a desenvolver percepção de espaço e proporção 🎨 #arte #proporcao #tutorial",
      "Ideias de sketching rápido com [tema] 🖌️ #arte #sketch #criatividade",
      "Como [tema] inspira arte abstrata 🎨 #arte #abstrato #inspiracao",
      "Top 5 combinações de cores para [tema] 🖌️ #arte #cores #criatividade",
      "Como [tema] transforma seu portfólio artístico 🎨 #arte #portfolio #inspiracao",
      "Dicas para retratar [tema] em retratos realistas 🖌️ #arte #retrato #tutorial",
      "Como [tema] pode ser usado em graffiti e street art 🎨 #arte #graffiti #criatividade",
      "Ideias de exposições virtuais usando [tema] 🖌️ #arte #exposicao #virtual",
      "Como [tema] mantém sua criatividade ativa todos os dias 🎨 #arte #criatividade #inspiracao",
      "Dicas de técnicas de iluminação para [tema] 🖌️ #arte #iluminacao #tutorial",
      "Como [tema] pode ser interpretado com diferentes materiais 🎨 #arte #materiais #criatividade",
      "Top 5 exercícios para melhorar suas obras com [tema] 🖌️ #arte #exercicios #tutorial",
      "Como [tema] inspira ilustrações para jogos e animações 🎨 #arte #jogos #criatividade",
      "Dicas de desenho digital para capturar [tema] 🖌️ #arte #digital #tutorial",
      "Como [tema] ajuda a criar obras emocionantes e expressivas 🎨 #arte #emocao #criatividade",
      "Top 10 técnicas clássicas para [tema] 🖌️ #arte #classico #tutorial",
      "Como [tema] transforma simples rabiscos em obras completas 🎨 #arte #desenho #criatividade",
      "Dicas para pintar [tema] com tinta a óleo 🖌️ #arte #oleo #tutorial",
      "Como [tema] ajuda a desenvolver estilo próprio 🎨 #arte #estilo #criatividade",
      "Top 5 ideias de composição artística com [tema] 🖌️ #arte #composicao #tutorial",
      "Como [tema] inspira ilustrações minimalistas 🎨 #arte #minimalismo #criatividade",
      "Dicas para criar séries de [tema] 🖌️ #arte #serie #inspiracao",
      "Como [tema] pode ser aplicado em design de interiores 🎨 #arte #interiores #criatividade",
      "Top 5 ideias de projetos colaborativos com [tema] 🖌️ #arte #colaborativo #tutorial",
      "Como [tema] influencia storytelling visual 🎨 #arte #historia #criatividade",
      "Dicas de técnicas mistas para criar [tema] 🖌️ #arte #tecnicas #tutorial",
      "Como [tema] pode ser usado para ilustrações educativas 🎨 #arte #educacao #criatividade",
      "Top 10 ideias de pintura para iniciantes com [tema] 🖌️ #arte #iniciante #tutorial",
      "Como [tema] transforma suas ideias em arte conceitual 🎨 #arte #conceito #criatividade",
      "Dicas de materiais alternativos para explorar [tema] 🖌️ #arte #materiais #criatividade",
      "Como [tema] inspira novas tendências de design 🎨 #arte #tendencias #criatividade",
      "Top 5 exercícios diários para praticar [tema] 🖌️ #arte #exercicios #tutorial",
      "Como [tema] transforma simples esboços em grandes obras 🎨 #arte #desenho #criatividade",
      "Dicas para capturar [tema] em ambientes externos e internos 🖌️ #arte #ambientes #tutorial",
      "Como [tema] mantém artistas engajados e motivados 🎨 #arte #motivacao #criatividade",
      "Top 10 inspirações históricas para [tema] 🖌️ #arte #historico #inspiracao",
      "Como [tema] pode ser reinterpretado de forma moderna 🎨 #arte #moderno #criatividade",
      "Dicas de iluminação natural para destacar [tema] 🖌️ #arte #iluminacao #tutorial",
      "Como [tema] pode ser usado para criar estampas e padrões 🎨 #arte #padroes #criatividade",
      "Top 5 exercícios de sketch rápido com [tema] 🖌️ #arte #sketch #tutorial",
      "Como [tema] inspira fotografia artística 🎨 #arte #fotografia #inspiracao",
      "Dicas para criar texturas incríveis com [tema] 🖌️ #arte #textura #tutorial",
      "Como [tema] mantém sua criatividade fluindo todos os dias 🎨 #arte #criatividade #inspiracao",
      "Top 10 técnicas de mistura de cores para [tema] 🖌️ #arte #cores #tutorial",
      "Como [tema] pode ser aplicado em animações e motion graphics 🎨 #arte #animacao #criatividade",
      "Dicas para transformar [tema] em arte digital avançada 🖌️ #arte #digital #tutorial",
      "Como [tema] ajuda a criar portfólio impressionante 🎨 #arte #portfolio #criatividade",
      "Top 5 técnicas de sombreamento e luz para [tema] 🖌️ #arte #sombreamento #tutorial",
      "Como [tema] pode ser usado para storytelling visual interativo 🎨 #arte #interativo #criatividade"
    ]
  }
};
