export const TEMPLATES = {
  beleza: {
    post: [
      "Dicas incríveis para cuidar de [tema] todos os dias ✨ #beleza #cuidadoscomapele #skincare",
      "Transforme seu visual com [tema] 💄 #makeup #beleza #dicas",
      "Segredo para manter [tema] saudável e brilhante 🌟 #beleza #cabelosaudavel #haircare",
      "Como [tema] pode melhorar sua rotina de beleza #beleza #rotinadebeleza #cuidados",
      "Aprenda truques de maquiagem usando [tema] 💋 #makeup #beleza #dicasdemakeup",
      "Produtos essenciais para realçar [tema] 🛍️ #beleza #produtos #skincare",
      "Passo a passo para cuidar de [tema] em casa 🏠 #beleza #cuidados #tutorial",
      "Como [tema] ajuda a manter a pele jovem #beleza #antienvelhecimento #skincare",
      "Inspiração de looks usando [tema] 💄 #beleza #lookdodia #maquiagem",
      "Erros comuns ao cuidar de [tema] e como evitá-los ❌ #beleza #dicas #skincare",
      "Receitas caseiras para melhorar [tema] naturalmente 🌿 #beleza #cuidadosnaturais #diy",
      "Como [tema] pode deixar seu cabelo mais saudável 💇 #beleza #haircare #cabelo",
      "Tendências de maquiagem usando [tema] este ano 💋 #beleza #makeuptrends #dicas",
      "Rotina diária para manter [tema] perfeito ✨ #beleza #cuidados #rotina",
      "5 produtos indispensáveis para [tema] 🛍️ #beleza #skincare #makeup",
      "Como [tema] melhora sua autoestima 💖 #beleza #autocuidado #bemestar",
      "Segredos de profissionais para cuidar de [tema] 👩‍🎨 #beleza #profissionais #dicas",
      "Dicas rápidas para [tema] antes de sair de casa 🚀 #beleza #makeup #rotina",
      "Como [tema] ajuda a proteger a pele do sol ☀️ #beleza #skincare #cuidados",
      "Transforme sua pele com [tema] em 7 dias ✨ #beleza #skincare #cuidados",
      "Como [tema] deixa suas unhas mais fortes 💅 #beleza #unhas #nailcare",
      "Makeup hacks usando [tema] que você precisa conhecer 💄 #beleza #dicas #makeuphacks",
      "Cuidados noturnos para [tema] 🌙 #beleza #rotinanoite #skincare",
      "Como [tema] ajuda a reduzir sinais de cansaço 😌 #beleza #bemestar #cuidados",
      "5 truques de beleza usando [tema] #beleza #dicas #makeup",
      "Transforme seu cabelo com [tema] em minutos 💇‍♀️ #beleza #haircare #cabelo",
      "Como [tema] melhora a hidratação da pele 💧 #beleza #cuidados #skincare",
      "Produtos naturais para cuidar de [tema] 🍃 #beleza #natural #cuidados",
      "Como [tema] deixa sua maquiagem mais duradoura 💄 #beleza #makeup #dicas",
      "Rotina simples para manter [tema] saudável todos os dias 🕒 #beleza #cuidados #skincare",
      "Dicas de especialistas para cuidar de [tema] 👩‍⚕️ #beleza #profissionais #dicas",
      "Como [tema] ajuda a combater acne e imperfeições 🌿 #beleza #skincare #cuidados",
      "Makeup tutorial usando [tema] passo a passo 💄 #beleza #tutorial #makeup",
      "Como [tema] melhora a elasticidade da pele ✨ #beleza #skincare #cuidados",
      "Segredos de beleza antiga usando [tema] 🏺 #beleza #dicas #cuidados",
      "Como [tema] ajuda a revitalizar cabelos danificados 💇 #beleza #haircare #cabelo",
      "Dicas rápidas para [tema] no dia a dia 🕒 #beleza #rotina #cuidados",
      "Transforme suas unhas com [tema] 💅 #beleza #nailcare #unhas",
      "Como [tema] ajuda a reduzir rugas e linhas finas ✨ #beleza #skincare #antiaging",
      "Segredos de maquiagem usando [tema] para festas 💄 #beleza #makeup #festas",
      "Cuidados de pele essenciais com [tema] 🌿 #beleza #skincare #cuidados",
      "Como [tema] ajuda a dar brilho natural ao cabelo 💇 #beleza #haircare #cabelo",
      "Dicas de beleza para quem tem pouco tempo ⏱️ #beleza #rotina #dicas",
      "Como [tema] pode melhorar a textura da pele ✨ #beleza #skincare #cuidados",
      "Técnicas de maquiagem usando [tema] que funcionam 💄 #beleza #makeup #dicas",
      "Como [tema] ajuda a prevenir ressecamento da pele 💧 #beleza #skincare #cuidados",
      "Cuidados semanais para [tema] 🗓️ #beleza #rotina #cuidados",
      "Como [tema] melhora a saúde do cabelo 💇‍♀️ #beleza #haircare #cabelo",
      "Dicas de especialistas: [tema] para pele perfeita 👩‍⚕️ #beleza #skincare #profissionais",
      "Como [tema] ajuda a criar maquiagem duradoura 💄 #beleza #makeup #dicas",
      "Rotina matinal usando [tema] 🌞 #beleza #skincare #rotina",
      "Segredos de beleza para [tema] que funcionam 💖 #beleza #dicas #cuidados",
      "Como [tema] ajuda a equilibrar oleosidade da pele 🌿 #beleza #skincare #cuidados",
      "Dicas de cuidado capilar usando [tema] 💇 #beleza #haircare #cabelo",
      "Como [tema] transforma sua maquiagem diária 💄 #beleza #makeup #rotina",
      "Segredos de spa em casa usando [tema] 🛁 #beleza #cuidados #dicas",
      "Como [tema] ajuda a fortalecer unhas frágeis 💅 #beleza #nailcare #unhas",
      "Makeup essentials: [tema] que não podem faltar 💄 #beleza #makeup #essenciais",
      "Como [tema] ajuda a hidratar profundamente a pele 💧 #beleza #skincare #cuidados",
      "Rotina simples de beleza usando [tema] 🕒 #beleza #rotina #dicas",
      "Como [tema] melhora o brilho natural da pele ✨ #beleza #skincare #cuidados",
      "Dicas de maquiagem rápida usando [tema] 💄 #beleza #makeup #rapido",
      "Como [tema] ajuda a reduzir olheiras e sinais de cansaço 😌 #beleza #skincare #cuidados",
      "Segredos para cabelo saudável usando [tema] 💇 #beleza #haircare #cabelo",
      "Como [tema] transforma sua rotina de cuidados diários 🌿 #beleza #rotina #cuidados",
      "Makeup hacks com [tema] para iniciantes 💄 #beleza #makeup #dicas",
      "Como [tema] ajuda a controlar frizz e volume 💇 #beleza #haircare #cabelo",
      "Dicas de beleza natural com [tema] 🍃 #beleza #natural #cuidados",
      "Como [tema] melhora a firmeza da pele ✨ #beleza #skincare #cuidados",
      "Transforme seu look com [tema] em minutos 💄 #beleza #makeup #dicas",
      "Como [tema] ajuda a revitalizar pele cansada 😌 #beleza #skincare #cuidados",
      "Rotina de spa em casa usando [tema] 🛁 #beleza #cuidados #bemestar",
      "Como [tema] ajuda a manter cabelos coloridos vibrantes 💇 #beleza #haircare #cabelo",
      "Dicas de maquiagem para pele sensível usando [tema] 💄 #beleza #makeup #cuidados",
      "Como [tema] ajuda a suavizar linhas de expressão ✨ #beleza #skincare #antiaging",
      "Segredos para unhas perfeitas com [tema] 💅 #beleza #nailcare #unhas",
      "Como [tema] ajuda a melhorar a absorção de produtos de beleza 💧 #beleza #skincare #dicas",
      "Dicas de beleza rápida para mulheres ocupadas ⏱️ #beleza #rotina #cuidados",
      "Como [tema] ajuda a proteger a pele de poluentes 🌿 #beleza #skincare #cuidados",
      "Técnicas de maquiagem usando [tema] para olhos incríveis 💄 #beleza #makeup #tutorial",
      "Como [tema] ajuda a manter cabelo hidratado 💇‍♀️ #beleza #haircare #cuidados",
      "Rotina de cuidados noturnos usando [tema] 🌙 #beleza #skincare #rotina",
      "Como [tema] transforma sua rotina de skincare diária 💧 #beleza #skincare #cuidados",
      "Dicas de beleza para pele madura usando [tema] ✨ #beleza #skincare #antiaging",
      "Como [tema] ajuda a manter unhas fortes e saudáveis 💅 #beleza #nailcare #cuidados",
      "Segredos para maquiagem perfeita usando [tema] 💄 #beleza #makeup #dicas",
      "Como [tema] ajuda a reduzir vermelhidão da pele 🌿 #beleza #skincare #cuidados",
      "Dicas de spa caseiro usando [tema] 🛁 #beleza #cuidados #bemestar",
      "Como [tema] ajuda a manter a pele macia e hidratada 💧 #beleza #skincare #cuidados",
      "Rotina simples de beleza matinal usando [tema] 🌞 #beleza #rotina #skincare",
      "Como [tema] transforma sua pele em poucos dias ✨ #beleza #skincare #dicas"
    ]
  }
};
