// ---------- TEMPLATES ----------
export const TEMPLATES = {
  culinaria: {
    post: [
      "3 motivos para amar [tema] na cozinha 🍳 Receita rápida e sabor irresistível! #culinaria #receita #gastronomia",
      "Você já experimentou [tema]? 😋 Comente sua receita favorita! #foodlover #cozinha #receitas",
      "Dica rápida: [tema] deixa qualquer refeição mais especial. #culinaria #dicas #chef",
      "Antes e depois: veja como [tema] transforma sua cozinha! #gastronomia #foodporn",
      "Receita express: aprenda [tema] em menos de 15 minutos! #receitafacil #culinaria",
      "Transforme seu jantar com [tema] hoje mesmo. #jantar #culinariaemcasa",
      "Segredo da cozinha: [tema] é o toque final perfeito. #chef #culinaria #foodtips",
      "Refeição completa: como [tema] faz toda diferença. #receitasaudavel #culinaria",
      "Aproveite [tema] para criar pratos incríveis. #cozinha #gastronomia",
      "Aprenda [tema] e impressione sua família! #culinaria #foodlover #receitas",
      "Experimente [tema] para um sabor único e delicioso. #delicious #culinaria #receitafacil",
      "Dica de chef: como [tema] pode elevar suas receitas. #chef #culinaria #cozinhaprofissional",
      "Receita rápida de [tema] que todos vão adorar. #culinaria #receitarapida #foodporn",
      "Inove na cozinha usando [tema] de forma criativa. #gastronomia #culinaria #receitascriativas",
      "Cozinhar com [tema] nunca foi tão fácil! #culinaria #cozinhaemcasa",
      "Receitas simples e deliciosas com [tema]. #culinaria #foodlover",
      "Aprenda truques de cozinha usando [tema]. #chef #culinaria #dicas",
      "Como [tema] transforma pratos comuns em especiais. #culinaria #gastronomia",
      "Delícias em minutos: receitas com [tema]. #culinaria #receitafacil",
      "O segredo do sabor: [tema] na sua mesa. #culinaria #foodlover #dicasdechef",
      "Prato perfeito: inclua [tema] na sua receita hoje. #culinaria #receitas #gastronomia",
      "Receitas irresistíveis com [tema] para qualquer ocasião. #culinaria #foodporn",
      "Dicas rápidas para usar [tema] sem complicações. #culinaria #cozinhafacil",
      "A magia do [tema] na cozinha: fácil e saborosa. #culinaria #receitas #gastronomia",
      "Receitas de família com [tema]: tradição e sabor. #culinaria #receitasdefamilia",
      "Transforme qualquer refeição com [tema] agora. #culinaria #foodlover",
      "Inspiração do dia: crie algo novo com [tema]. #culinaria #gastronomia",
      "Como impressionar usando apenas [tema] na receita. #culinaria #chef #receitas",
      "Sugestões deliciosas com [tema] para o jantar. #culinaria #foodporn",
      "Receita prática de [tema] que todos vão adorar. #culinaria #receitarapida",
      "Receitas gourmet fáceis com [tema]. #culinaria #gourmet",
      "Aposte em [tema] e surpreenda sua família. #culinaria #receitas",
      "Receitas rápidas e saborosas com [tema]. #culinaria #foodlover",
      "Dicas de chef: receitas incríveis com [tema]. #culinaria #chef",
      "Como [tema] pode salvar o seu jantar em minutos. #culinaria #receitarapida",
      "Receitas saudáveis com [tema] para o dia a dia. #culinaria #saudavel",
      "O poder do [tema] em pratos simples e deliciosos. #culinaria #foodlover",
      "Receitas criativas com [tema] para impressionar amigos. #culinaria #receitascriativas",
      "Como preparar [tema] de forma fácil e rápida. #culinaria #cozinhafacil",
      "Sugestão do dia: prato incrível com [tema]. #culinaria #foodporn",
      "Aprenda a usar [tema] como um verdadeiro chef. #culinaria #chef",
      "Dicas de preparo: [tema] para receitas perfeitas. #culinaria #cozinhaprofissional",
      "Receita express com [tema]: sabor em minutos. #culinaria #receitarapida",
      "Como [tema] transforma o café da manhã em especial. #culinaria #breakfast",
      "Receita simples de [tema] que todos vão adorar. #culinaria #foodlover",
      "Experimente [tema] e surpreenda no almoço. #culinaria #receitas",
      "Receitas incríveis com [tema] para qualquer ocasião. #culinaria #gastronomia",
      "O segredo de uma refeição deliciosa: [tema]. #culinaria #foodporn",
      "Aprenda receitas rápidas usando [tema] hoje mesmo. #culinaria #receitarapida",
      "Receitas irresistíveis com [tema] que você precisa testar. #culinaria #chef",
      "Dicas de cozinha: como [tema] muda tudo. #culinaria #cozinhafacil",
      "Receita prática e saborosa com [tema] em menos de 20 minutos. #culinaria #receitarapida",
      "Receitas doces incríveis com [tema] 🍰 #culinaria #doces #receitas",
      "Aprenda a preparar [tema] como um chef profissional. #chef #culinaria #gastronomia",
      "Como [tema] transforma refeições simples em memoráveis. #culinaria #foodlover",
      "Receita rápida de [tema] para dias corridos. #culinaria #receitarapida",
      "Sugestão de brunch delicioso com [tema]. #culinaria #brunch #receitas",
      "Como [tema] pode ser usado em pratos vegetarianos. #culinaria #vegetariano",
      "Receitas de [tema] para jantares românticos. #culinaria #foodlover",
      "Dicas de chef: combinando [tema] com outros ingredientes. #culinaria #chef",
      "Como fazer [tema] em menos de 30 minutos. #culinaria #receitarapida",
      "Transforme [tema] em sobremesas irresistíveis. #culinaria #doces #receitas",
      "Receita saudável de [tema] para o café da manhã. #culinaria #saudavel",
      "Como usar [tema] para criar pratos gourmet. #culinaria #gourmet",
      "Sugestões de almoço rápido com [tema]. #culinaria #receitarapida",
      "Receitas com [tema] para toda a família. #culinaria #foodlover",
      "Como preparar [tema] sem erros. #culinaria #dicasdechef",
      "Receita prática de [tema] para iniciantes. #culinaria #cozinhafacil",
      "Dicas de chef para transformar [tema] em prato gourmet. #culinaria #chef",
      "Receitas criativas com [tema] que impressionam. #culinaria #receitascriativas",
      "Sugestão de jantar rápido com [tema]. #culinaria #receitarapida",
      "Como [tema] pode ser protagonista em sua cozinha. #culinaria #foodlover",
      "Receitas de [tema] fáceis e saborosas. #culinaria #culinariaemcasa",
      "Dicas de preparo rápido com [tema]. #culinaria #cozinhafacil",
      "Receitas deliciosas de [tema] para qualquer ocasião. #culinaria #gastronomia",
      "Como [tema] eleva o sabor de pratos simples. #culinaria #foodlover",
      "Sugestões de pratos com [tema] para o almoço. #culinaria #receitarapida",
      "Receitas de festa usando [tema]. #culinaria #festas #foodporn",
      "Como usar [tema] para criar molhos incríveis. #culinaria #dicasdechef",
      "Receita express de [tema] para iniciantes. #culinaria #cozinhafacil",
      "Sugestões de sobremesas com [tema]. #culinaria #doces #receitas",
      "Como combinar [tema] com outros ingredientes. #culinaria #chef",
      "Receitas de [tema] que toda família vai amar. #culinaria #foodlover",
      "Dicas para usar [tema] no dia a dia. #culinaria #cozinhafacil",
      "Receitas rápidas e práticas de [tema]. #culinaria #receitarapida",
      "Como preparar [tema] de forma saudável. #culinaria #saudavel",
      "Sugestão de jantar leve com [tema]. #culinaria #receitas",
      "Receitas gourmet com [tema] que impressionam. #culinaria #gourmet",
      "Como usar [tema] para criar pratos balanceados. #culinaria #saudavel",
      "Dicas de chef: receitas simples de [tema] que impressionam. #culinaria #chef",
      "Como preparar [tema] para ocasiões especiais. #culinaria #gastronomia",
      "Receitas rápidas de [tema] para café da manhã. #culinaria #breakfast",
      "Como [tema] pode transformar refeições comuns. #culinaria #foodlover",
      "Sugestões de cardápio semanal com [tema]. #culinaria #receitas",
      "Receitas saborosas com [tema] para qualquer época do ano. #culinaria #foodporn",
      "Como escolher o melhor [tema] para suas receitas. #culinaria #chef",
      "Como preparar [tema] de forma prática e deliciosa. #culinaria #cozinhafacil",
      "Receitas de [tema] que impressionam convidados. #culinaria #gourmet",
      "Sugestões de pratos veganos com [tema]. #culinaria #vegano #receitas",
      "Como [tema] pode ser usado em sopas e saladas. #culinaria #saudavel",
      "Receitas rápidas com [tema] para almoço e jantar. #culinaria #receitarapida",
      "Como usar [tema] para criar pratos internacionais. #culinaria #gastronomia",
      "Receitas fáceis de [tema] para iniciantes. #culinaria #cozinhafacil",
      "Dicas rápidas de chef para usar [tema]. #culinaria #chef",
      "Como [tema] pode ser ingrediente principal em pratos incríveis. #culinaria #foodlover",
      "Receitas de [tema] deliciosas e rápidas. #culinaria #receitarapida",
      "Sugestão de brunch com [tema] para o fim de semana. #culinaria #brunch",
      "Como [tema] transforma pratos simples em memoráveis. #culinaria #foodporn",
      "Receitas criativas de [tema] para qualquer refeição. #culinaria #receitascriativas",
      "Como preparar [tema] de forma rápida e prática. #culinaria #cozinhafacil",
      "Sugestões de pratos saudáveis com [tema]. #culinaria #saudavel",
      "Receitas irresistíveis de [tema] para toda família. #culinaria #foodlover"
    ]
  }
};
