export const TEMPLATES = {
  desenvolvimentoPessoal: {
    post: [
      "Como [tema] pode transformar sua vida diariamente ✨ #desenvolvimentopessoal #motivacao #autocrescimento",
      "5 hábitos poderosos de [tema] para alcançar seus objetivos 💪 #autodisciplina #crescimento",
      "Dicas para melhorar sua produtividade usando [tema] 📝 #desenvolvimentopessoal #foco #organizacao",
      "Como [tema] ajuda a lidar melhor com desafios e obstáculos 🌱 #resiliencia #motivacao",
      "Transforme sua mente e seus resultados com [tema] 💡 #mentalidade #autoconhecimento",
      "A importância de [tema] para alcançar equilíbrio emocional ⚖️ #inteligenciaemocional #bemestar",
      "Como [tema] inspira criatividade e novas ideias 💭 #criatividade #desenvolvimento",
      "Passo a passo para implementar [tema] na sua rotina diária 📅 #disciplina #autocrescimento",
      "Como [tema] ajuda a construir hábitos saudáveis e consistentes 🥗 #saude #habitos",
      "Top 5 maneiras de aplicar [tema] na sua vida pessoal e profissional 🚀 #crescimento #sucesso",
      "Como [tema] melhora sua autoconfiança e autoestima 💎 #autoconfianca #desenvolvimentopessoal",
      "Dicas práticas de [tema] para quem quer evoluir constantemente 🏋️‍♂️ #motivacao #progresso",
      "Como [tema] pode mudar sua perspectiva sobre desafios 🌄 #mentalidade #crescimento",
      "Inspire-se com exemplos de [tema] que mudaram vidas ✨ #inspiracao #desenvolvimentopessoal",
      "Como [tema] ajuda a manter foco em objetivos de longo prazo 🎯 #foco #disciplina",
      "Estratégias de [tema] para melhorar relacionamentos interpessoais 🤝 #inteligenciaemocional #comunicacao",
      "Como [tema] pode ser aplicado em momentos de estresse e ansiedade 😌 #bemestar #mindfulness",
      "Passos para desenvolver [tema] de forma consistente e efetiva 📈 #crescimento #autodesenvolvimento",
      "Como [tema] influencia diretamente sua motivação diária 🔥 #motivacao #progresso",
      "Dicas de leitura e estudo sobre [tema] 📚 #conhecimento #aprendizado",
      "Como [tema] ajuda a definir prioridades e metas claras 🗂️ #organizacao #planejamento",
      "Exercícios simples para praticar [tema] todos os dias 💡 #autoconsciencia #desenvolvimentopessoal",
      "Como [tema] fortalece sua resiliência emocional 💪 #resiliencia #bemestar",
      "Top 5 atitudes de pessoas que aplicam [tema] com sucesso 🌟 #motivacao #crescimento",
      "Como [tema] contribui para a inteligência emocional no trabalho 🏢 #autodesenvolvimento #profissional",
      "Dicas para incorporar [tema] na sua rotina matinal ☀️ #habitos #produtividade",
      "Como [tema] transforma pensamentos negativos em positivos 🌈 #mentalidade #positividade",
      "Estratégias de [tema] para aumentar sua autoconfiança diariamente 💎 #autoconfianca #crescimento",
      "Como [tema] ajuda a lidar com críticas e feedbacks construtivos 📝 #autoconsciencia #resiliencia",
      "Top 5 exercícios de reflexão sobre [tema] 🧘‍♂️ #mindfulness #desenvolvimentopessoal",
      "Como [tema] melhora a comunicação e relacionamentos interpessoais 💬 #inteligenciaemocional #comunicacao",
      "Dicas práticas para desenvolver [tema] em situações de pressão 🔥 #resiliencia #autocrescimento",
      "Como [tema] ajuda a criar hábitos produtivos e consistentes 📅 #disciplina #progresso",
      "Estratégias para usar [tema] no planejamento de metas a longo prazo 🎯 #objetivos #autodesenvolvimento",
      "Como [tema] influencia sua capacidade de tomar decisões melhores 💡 #mentalidade #crescimento",
      "Top 5 livros sobre [tema] que você precisa ler 📚 #conhecimento #desenvolvimentopessoal",
      "Como [tema] contribui para sua saúde mental e emocional 🧠 #bemestar #mindfulness",
      "Dicas de mindset positivo aplicando [tema] diariamente 🌞 #motivacao #mentalidade",
      "Como [tema] ajuda a superar bloqueios e procrastinação ⏳ #produtividade #crescimento",
      "Estratégias de [tema] para melhorar habilidades de liderança 👑 #lideranca #autodesenvolvimento",
      "Como [tema] fortalece sua disciplina e consistência diária 💪 #habitos #autocrescimento",
      "Dicas para aplicar [tema] no desenvolvimento pessoal e profissional 🌱 #crescimento #sucesso",
      "Como [tema] transforma desafios em oportunidades de crescimento 🚀 #resiliencia #motivacao",
      "Passos práticos para implementar [tema] em sua vida diária 📌 #autodesenvolvimento #habitos",
      "Como [tema] ajuda a aumentar foco e produtividade 📝 #disciplina #crescimento",
      "Top 5 técnicas para praticar [tema] todos os dias 🧘‍♀️ #mindfulness #autoconsciencia",
      "Como [tema] inspira novas ideias e criatividade 💡 #criatividade #desenvolvimento",
      "Dicas de planejamento usando [tema] para alcançar objetivos claros 🎯 #planejamento #sucesso",
      "Como [tema] fortalece a inteligência emocional e social 🤝 #autocrescimento #relacionamentos",
      "Estratégias simples para manter [tema] ativo diariamente 🌟 #motivacao #consistencia",
      "Como [tema] ajuda a desenvolver habilidades de liderança 👔 #lideranca #desenvolvimento",
      "Dicas práticas para integrar [tema] na sua rotina de estudos 📚 #conhecimento #aprendizado",
      "Como [tema] contribui para um mindset positivo e resiliente 🌈 #mentalidade #crescimento",
      "Top 5 hábitos de pessoas que aplicam [tema] com sucesso 🌟 #motivacao #autodesenvolvimento",
      "Como [tema] ajuda a gerenciar melhor o tempo e prioridades ⏰ #produtividade #organizacao",
      "Estratégias para usar [tema] na resolução de problemas complexos 🧩 #mentalidade #crescimento",
      "Como [tema] fortalece autoconhecimento e consciência pessoal 💡 #autoconsciencia #desenvolvimentopessoal",
      "Dicas de exercícios para praticar [tema] em casa 🏡 #autocrescimento #habitos",
      "Como [tema] contribui para desenvolvimento profissional e pessoal 🚀 #sucesso #crescimento",
      "Top 5 reflexões sobre [tema] para melhorar sua vida ✨ #mindfulness #desenvolvimentopessoal",
      "Como [tema] inspira autoconfiança e autoestima 💎 #autoconfianca #motivacao",
      "Dicas de mindset para aplicar [tema] em situações difíceis 🌟 #resiliencia #mentalidade",
      "Como [tema] ajuda a criar hábitos consistentes e saudáveis 🥗 #habitos #desenvolvimentopessoal",
      "Estratégias de [tema] para melhorar relações interpessoais 💬 #inteligenciaemocional #relacionamentos",
      "Como [tema] contribui para foco e disciplina diária 📝 #produtividade #autocrescimento",
      "Top 5 formas de aplicar [tema] para resultados imediatos 🌱 #autodesenvolvimento #motivacao",
      "Como [tema] fortalece a capacidade de tomar decisões conscientes 💡 #mentalidade #crescimento",
      "Dicas de meditação e mindfulness usando [tema] 🧘‍♂️ #bemestar #autoconsciencia",
      "Como [tema] ajuda a superar medos e inseguranças 🌄 #coragem #desenvolvimentopessoal",
      "Estratégias práticas para aplicar [tema] no trabalho e estudos 💼 #produtividade #crescimento",
      "Como [tema] fortalece a resiliência emocional e mental 🧠 #resiliencia #motivacao",
      "Top 5 exercícios de reflexão e autoconhecimento com [tema] 🌱 #mindfulness #desenvolvimento",
      "Como [tema] ajuda a definir metas claras e alcançáveis 🎯 #planejamento #autodesenvolvimento",
      "Dicas para manter [tema] ativo mesmo em dias difíceis 💪 #motivacao #consistencia",
      "Como [tema] contribui para desenvolvimento de habilidades sociais 🤝 #inteligenciaemocional #relacionamentos",
      "Estratégias de [tema] para alcançar alta performance diária 🚀 #produtividade #autocrescimento",
      "Como [tema] transforma pequenos hábitos em grandes resultados 🌟 #autodesenvolvimento #crescimento",
      "Top 5 livros recomendados sobre [tema] 📚 #conhecimento #desenvolvimentopessoal",
      "Como [tema] ajuda a manter foco em metas e prioridades 🎯 #disciplina #crescimento",
      "Dicas práticas para aplicar [tema] em situações de estresse 🌿 #bemestar #resiliencia",
      "Como [tema] inspira mudanças positivas na vida pessoal e profissional 🌈 #autocrescimento #motivacao",
      "Estratégias de [tema] para desenvolver inteligência emocional e social 🤝 #relacionamentos #desenvolvimento",
      "Como [tema] contribui para criar mindset vencedor e motivador 🔥 #mentalidade #motivacao",
      "Top 5 atitudes de sucesso baseadas em [tema] 🌟 #autodesenvolvimento #crescimento",
      "Como [tema] ajuda a organizar rotina e hábitos diários 📅 #produtividade #habitos",
      "Dicas de exercícios diários para praticar [tema] 🧘‍♀️ #autoconsciencia #mindfulness",
      "Como [tema] fortalece autoconfiança e habilidades pessoais 💎 #autoconfianca #desenvolvimento",
      "Estratégias simples para aplicar [tema] em qualquer área da vida 🌱 #autocrescimento #motivacao",
      "Como [tema] ajuda a superar procrastinação e focar em resultados ⏳ #produtividade #crescimento",
      "Top 5 formas criativas de praticar [tema] diariamente 💡 #mindset #autodesenvolvimento",
      "Como [tema] transforma desafios em oportunidades de aprendizado 🚀 #resiliencia #motivacao",
      "Dicas práticas de implementação de [tema] para iniciantes 🌟 #autocrescimento #desenvolvimentopessoal",
      "Como [tema] ajuda a criar equilíbrio entre vida pessoal e profissional ⚖️ #bemestar #crescimento",
      "Estratégias de [tema] para desenvolver hábitos duradouros e consistentes 💪 #habitos #autodesenvolvimento",
      "Como [tema] inspira criatividade, inovação e novas ideias 💡 #criatividade #motivacao",
      "Top 5 reflexões sobre [tema] para melhorar mindset diariamente 🌱 #mentalidade #autoconsciencia",
      "Como [tema] fortalece disciplina, foco e produtividade diária 📝 #produtividade #crescimento"
    ]
  }
};
