export const TEMPLATES = {
  entretenimento: {
    post: [
      "Top 5 filmes sobre [tema] que você precisa assistir 🍿 #entretenimento #filmes #cinema",
      "Como [tema] está dominando as séries do momento 📺 #series #entretenimento #tv",
      "Dicas de livros incríveis sobre [tema] 📚 #livros #leitura #entretenimento",
      "Jogos imperdíveis para quem ama [tema] 🎮 #games #diversao #entretenimento",
      "Músicas sobre [tema] que você vai adorar ouvir 🎵 #musica #playlist #entretenimento",
      "Fatos curiosos sobre [tema] que você não sabia 🤯 #curiosidades #entretenimento #diversao",
      "Como [tema] está inspirando artistas pelo mundo 🎨 #arte #criatividade #entretenimento",
      "As melhores performances ao vivo sobre [tema] 🎤 #show #musica #entretenimento",
      "Top podcasts sobre [tema] que você precisa ouvir 🎧 #podcast #entretenimento #conhecimento",
      "Como [tema] está influenciando a cultura pop 🌟 #popculture #entretenimento #tendencias",
      "Filmes clássicos sobre [tema] que todos deveriam ver 🎬 #cinema #classicos #entretenimento",
      "Séries recentes sobre [tema] que estão bombando 📺 #series #tv #entretenimento",
      "Como [tema] mudou a história do entretenimento 🎭 #historia #cultura #entretenimento",
      "Dicas de apps de entretenimento para explorar [tema] 📱 #apps #diversao #entretenimento",
      "Top memes sobre [tema] que vão te fazer rir 😂 #memes #humor #entretenimento",
      "Shows e eventos imperdíveis sobre [tema] 🎉 #eventos #show #entretenimento",
      "Como [tema] está inspirando novos criadores de conteúdo 🌟 #criadores #conteudo #entretenimento",
      "Os melhores documentários sobre [tema] para assistir hoje 🎥 #documentario #entretenimento #curiosidades",
      "Top canais do YouTube sobre [tema] que você precisa conhecer 📹 #youtube #conteudo #entretenimento",
      "Como [tema] influenciou a moda e estilo 🌈 #moda #cultura #entretenimento",
      "Curiosidades sobre bastidores de [tema] 🎬 #bastidores #filmes #entretenimento",
      "Como [tema] está impactando a indústria musical 🎶 #musica #cultura #entretenimento",
      "Top eventos de [tema] que você não pode perder 🏟️ #eventos #diversao #entretenimento",
      "Os melhores artistas relacionados a [tema] 🎨 #arte #musica #entretenimento",
      "Como [tema] influenciou séries e filmes recentes 📺 #series #cinema #entretenimento",
      "Top celebridades fãs de [tema] 🌟 #celebridades #popculture #entretenimento",
      "Como [tema] está inspirando novos talentos no cinema 🎬 #cinema #talento #entretenimento",
      "Dicas de playlists para curtir [tema] 🎵 #musica #playlist #entretenimento",
      "Curiosidades engraçadas sobre [tema] 😂 #curiosidades #humor #entretenimento",
      "Os melhores trailers sobre [tema] que você precisa ver 🎥 #cinema #trailer #entretenimento",
      "Como [tema] está mudando a forma de consumir entretenimento 📱 #tecnologia #entretenimento #tendencias",
      "Top eventos de música relacionados a [tema] 🎤 #musica #eventos #entretenimento",
      "Como [tema] influencia a cultura geek 🎮 #geek #nerd #entretenimento",
      "Top atores e atrizes famosos por [tema] 🎭 #atores #cinema #entretenimento",
      "Como [tema] está presente nos games mais populares 🎮 #games #entretenimento #diversao",
      "Os melhores shows ao vivo relacionados a [tema] 🎶 #show #musica #entretenimento",
      "Dicas de livros para aprender mais sobre [tema] 📚 #leitura #livros #entretenimento",
      "Como [tema] inspira criações de arte digital 🎨 #arte #digital #entretenimento",
      "Top filmes de comédia sobre [tema] 😂 #humor #filmes #entretenimento",
      "Curiosidades históricas sobre [tema] 📜 #historia #curiosidades #entretenimento",
      "Como [tema] impactou a televisão moderna 📺 #tv #series #entretenimento",
      "Dicas de apps para explorar [tema] de forma divertida 📱 #apps #diversao #entretenimento",
      "Top podcasts engraçados sobre [tema] 🎧 #podcast #humor #entretenimento",
      "Como [tema] está inspirando memes virais 😂 #memes #internet #entretenimento",
      "Os melhores videoclipes sobre [tema] 🎵 #musica #videoclipe #entretenimento",
      "Como [tema] influencia a moda e lifestyle 🌟 #moda #cultura #entretenimento",
      "Top séries de drama sobre [tema] que você precisa assistir 📺 #series #drama #entretenimento",
      "Como [tema] está presente nos eventos de cultura pop 🌈 #popculture #eventos #entretenimento",
      "Dicas de canais de YouTube para explorar [tema] 📹 #youtube #conteudo #entretenimento",
      "Top atores de comédia relacionados a [tema] 😂 #atores #humor #entretenimento",
      "Como [tema] inspira novos criadores de conteúdo digital 🌟 #criadores #conteudo #entretenimento",
      "Os melhores festivais de música sobre [tema] 🎤 #festivais #musica #entretenimento",
      "Como [tema] influencia os games indie mais populares 🎮 #games #indie #entretenimento",
      "Top filmes de ação relacionados a [tema] 🎬 #acao #cinema #entretenimento",
      "Como [tema] impacta o mundo do streaming 📺 #streaming #series #entretenimento",
      "Dicas de playlists temáticas sobre [tema] 🎵 #musica #playlist #entretenimento",
      "Como [tema] inspirou artistas famosos 🎨 #arte #cultura #entretenimento",
      "Top documentários sobre [tema] que valem a pena assistir 🎥 #documentario #curiosidades #entretenimento",
      "Como [tema] está moldando o universo pop 🎭 #popculture #cultura #entretenimento",
      "Top séries de comédia sobre [tema] 😂 #series #humor #entretenimento",
      "Como [tema] influencia a criação de games online 🎮 #games #entretenimento #diversao",
      "Top livros de ficção sobre [tema] 📚 #leitura #livros #entretenimento",
      "Como [tema] está presente nos memes mais populares 😂 #memes #internet #entretenimento",
      "Dicas de eventos culturais sobre [tema] 🌟 #cultura #eventos #entretenimento",
      "Como [tema] inspirou obras de arte modernas 🎨 #arte #moderna #entretenimento",
      "Top artistas musicais relacionados a [tema] 🎵 #musica #artistas #entretenimento",
      "Como [tema] impacta a indústria do cinema 🎬 #cinema #industria #entretenimento",
      "Top programas de TV sobre [tema] 📺 #tv #programas #entretenimento",
      "Como [tema] está presente nas redes sociais 🌐 #socialmedia #entretenimento #tendencias",
      "Top shows de comédia relacionados a [tema] 😂 #show #humor #entretenimento",
      "Como [tema] influencia a cultura jovem 🌟 #cultura #jovem #entretenimento",
      "Dicas de apps para curtir [tema] de forma divertida 📱 #apps #diversao #entretenimento",
      "Como [tema] está presente em novelas e séries dramáticas 📺 #series #drama #entretenimento",
      "Top videoclipes sobre [tema] que você precisa assistir 🎵 #musica #videoclipes #entretenimento",
      "Como [tema] inspirou conteúdo viral na internet 🌐 #internet #viral #entretenimento",
      "Top eventos ao vivo relacionados a [tema] 🎤 #eventos #show #entretenimento",
      "Como [tema] influencia a moda pop 🌈 #moda #popculture #entretenimento",
      "Top jogos de tabuleiro inspirados em [tema] 🎲 #jogos #diversao #entretenimento",
      "Como [tema] impacta os quadrinhos e HQs 📚 #quadrinhos #hqs #entretenimento",
      "Top filmes de terror sobre [tema] 👻 #terror #cinema #entretenimento",
      "Como [tema] está presente em festivais internacionais 🌍 #festivais #cultura #entretenimento",
      "Top séries de ficção científica relacionadas a [tema] 🚀 #series #ficcao #entretenimento",
      "Como [tema] inspira novos talentos no YouTube 📹 #youtube #criadores #entretenimento",
      "Top livros de não-ficção sobre [tema] 📚 #livros #conhecimento #entretenimento",
      "Como [tema] influencia a criação de animações 🎨 #animacao #arte #entretenimento",
      "Top shows de música eletrônica relacionados a [tema] 🎶 #musica #festivais #entretenimento",
      "Como [tema] impacta o mercado de entretenimento digital 🌐 #digital #entretenimento #tendencias",
      "Top podcasts divertidos sobre [tema] 🎧 #podcast #humor #entretenimento",
      "Como [tema] inspira a criação de quadrinhos modernos 📚 #hqs #arte #entretenimento",
      "Top filmes premiados sobre [tema] 🏆 #cinema #premios #entretenimento",
      "Como [tema] está presente nos memes do TikTok 🎵 #tiktok #memes #entretenimento",
      "Top eventos esportivos relacionados a [tema] 🏟️ #esportes #eventos #entretenimento",
      "Como [tema] influencia o humor e o stand-up comedy 😂 #humor #comedy #entretenimento",
      "Top séries animadas sobre [tema] 🎨 #animacao #series #entretenimento",
      "Como [tema] inspira a criação de playlists musicais 🎵 #playlist #musica #entretenimento",
      "Top vídeos virais sobre [tema] 🌐 #viral #internet #entretenimento",
      "Como [tema] impacta a criação de conteúdo para streaming 📺 #streaming #conteudo #entretenimento",
      "Top filmes de aventura relacionados a [tema] 🏞️ #aventura #cinema #entretenimento",
      "Como [tema] está presente em reality shows 📺 #tv #reality #entretenimento",
      "Top documentários educativos sobre [tema] 🎥 #educativo #documentario #entretenimento",
      "Como [tema] influencia tendências de entretenimento jovem 🌟 #tendencias #cultura #entretenimento",
      "Top games mobile relacionados a [tema] 📱 #games #mobile #entretenimento",
      "Como [tema] inspira novos conteúdos para redes sociais 🌐 #criadores #digital #entretenimento",
      "Top shows de TV clássicos sobre [tema] 📺 #tv #classicos #entretenimento",
      "Como [tema] impacta a cultura nerd e geek 🎮 #geek #nerd #entretenimento",
      "Top videoclipes históricos sobre [tema] 🎵 #musica #historia #entretenimento",
      "Como [tema] influencia as séries de animação modernas 🎨 #animacao #series #entretenimento",
      "Top livros clássicos relacionados a [tema] 📚 #livros #classicos #entretenimento",
      "Como [tema] inspira eventos culturais ao redor do mundo 🌍 #cultura #eventos #entretenimento",
      "Top shows de mágica e ilusionismo relacionados a [tema] 🎩 #magia #show #entretenimento",
      "Como [tema] impacta a criação de vídeos curtos no TikTok 🎵 #tiktok #videos #entretenimento",
      "Top festivais de cinema sobre [tema] 🎬 #festivais #cinema #entretenimento",
      "Como [tema] influencia os memes no Instagram 😂 #instagram #memes #entretenimento",
      "Top séries de fantasia sobre [tema] 🧙‍♂️ #series #fantasia #entretenimento",
      "Como [tema] inspira conteúdo criativo para YouTube 📹 #youtube #criatividade #entretenimento"
    ]
  }
};
