export const TEMPLATES = {
  fitness: {
    post: [
      "Treino rápido de [tema] para resultados visíveis 💪 Inclua na sua rotina diária!",
      "Dica fitness: como [tema] ajuda a manter a forma.",
      "Treine com [tema] e veja resultados impressionantes.",
      "Antes e depois: [tema] que faz diferença na performance.",
      "Exercício rápido de [tema] para iniciantes.",
      "Potencialize seu treino usando [tema].",
      "Descubra os benefícios do [tema] diariamente.",
      "Rotina fitness: [tema] é essencial para resultados.",
      "Como [tema] melhora força e resistência.",
      "Treinos curtos e eficientes com [tema].",
      "Inclua [tema] na sua rotina e aumente sua energia.",
      "5 motivos para treinar [tema] todos os dias.",
      "Transforme seu corpo com apenas 10 minutos de [tema].",
      "O segredo para emagrecer usando [tema].",
      "Como [tema] melhora seu condicionamento físico.",
      "Treino de [tema] que qualquer iniciante consegue fazer.",
      "Dicas avançadas de [tema] para aumentar massa muscular.",
      "A importância do [tema] para a saúde cardiovascular.",
      "Como [tema] ajuda a reduzir o estresse e ansiedade.",
      "Melhore seu desempenho com exercícios de [tema].",
      "Treino funcional usando [tema] para resultados rápidos.",
      "Aumente sua resistência física com [tema].",
      "Desafio de 7 dias: faça [tema] todos os dias!",
      "Treino matinal com [tema] para começar bem o dia.",
      "Como combinar [tema] com alimentação saudável.",
      "Exercícios de [tema] que queimam mais calorias.",
      "Treine [tema] em casa sem equipamentos.",
      "Dicas para manter a motivação ao praticar [tema].",
      "Como [tema] fortalece músculos e articulações.",
      "5 erros comuns ao fazer [tema] e como evitá-los.",
      "O poder do [tema] para tonificar o corpo.",
      "Treino rápido de [tema] antes do trabalho.",
      "Como [tema] ajuda a prevenir lesões.",
      "Sugestão de treino completo com [tema].",
      "Benefícios mentais de praticar [tema].",
      "Desafio fitness: aprenda [tema] em 30 dias.",
      "Como o [tema] melhora a postura corporal.",
      "Treino de alta intensidade com [tema].",
      "Como adaptar [tema] para seu nível de fitness.",
      "Dicas para iniciantes começarem com [tema].",
      "Treino de [tema] para queimar gordura abdominal.",
      "Inclua [tema] para aumentar sua flexibilidade.",
      "Treino de [tema] para fortalecer pernas e glúteos.",
      "Como [tema] melhora a resistência muscular.",
      "Exercícios de [tema] para fazer em 15 minutos.",
      "Como combinar [tema] com cardio para resultados melhores.",
      "Rotina de [tema] para atletas iniciantes.",
      "Treino de [tema] que ajuda na recuperação muscular.",
      "Aumente a intensidade do [tema] com variações avançadas.",
      "Como [tema] ajuda na definição muscular.",
      "Treino rápido de [tema] para dias corridos.",
      "Exercícios de [tema] para melhorar equilíbrio e coordenação.",
      "Como [tema] acelera o metabolismo.",
      "Treino de [tema] para aumentar força sem equipamentos.",
      "Como [tema] contribui para saúde óssea.",
      "Desafio de 10 minutos: [tema] todos os dias.",
      "Treino de [tema] para reduzir medidas e tonificar.",
      "Dicas de postura correta ao praticar [tema].",
      "Exercícios de [tema] que você pode fazer no sofá!",
      "Como [tema] melhora desempenho em outros esportes.",
      "Treino de [tema] que não cansa mas traz resultados.",
      "Como combinar [tema] e alongamentos para melhor performance.",
      "Treino de [tema] para quem tem pouco tempo.",
      "Benefícios do [tema] para saúde mental e física.",
      "Como [tema] ajuda a aumentar energia e disposição.",
      "Treino de [tema] para tonificar braços e ombros.",
      "Sugestão de circuito de [tema] para iniciantes.",
      "Como [tema] pode ser feito em casa sem sair do lugar.",
      "Exercícios de [tema] que qualquer pessoa consegue fazer.",
      "Treino de [tema] para fortalecer core e abdômen.",
      "Como [tema] ajuda a prevenir dores nas costas.",
      "Dicas para evoluir no [tema] sem se machucar.",
      "Treino de [tema] que aumenta resistência cardiovascular.",
      "Como [tema] melhora coordenação motora.",
      "Treino de [tema] para queimar calorias rápido.",
      "Benefícios do [tema] para saúde do coração.",
      "Como adaptar [tema] para exercícios em dupla.",
      "Treino de [tema] que pode ser feito ao ar livre.",
      "Dicas para iniciantes não desistirem do [tema].",
      "Treino de [tema] para melhorar performance esportiva.",
      "Como [tema] ajuda na recuperação após treino intenso.",
      "Exercícios de [tema] que aumentam mobilidade articular.",
      "Treino de [tema] para fortalecer glúteos e coxas.",
      "Como [tema] pode ser incorporado à rotina diária.",
      "Treino de [tema] para queimar gordura localizada.",
      "Como variar o [tema] para não ficar monótono.",
      "Treino de [tema] em circuito para condicionamento físico.",
      "Dicas de respiração correta ao fazer [tema].",
      "Treino de [tema] que melhora postura e alinhamento.",
      "Como o [tema] ajuda a reduzir o risco de lesões.",
      "Exercícios de [tema] para todos os níveis de fitness.",
      "Treino de [tema] para iniciantes e avançados.",
      "Como [tema] ajuda a aumentar força de forma saudável.",
      "Treino de [tema] que pode ser feito em qualquer lugar.",
      "Dicas para manter constância ao praticar [tema].",
      "Treino de [tema] que melhora equilíbrio e força.",
      "Como [tema] ajuda a aumentar resistência em corridas.",
      "Treino de [tema] para emagrecimento saudável.",
      "Exercícios de [tema] para tonificar todo o corpo.",
      "Como [tema] melhora desempenho em esportes coletivos.",
      "Treino de [tema] que não precisa de academia.",
      "Sugestões de treinos rápidos de [tema] para dias corridos.",
      "Como [tema] ajuda a melhorar qualidade do sono.",
      "Treino de [tema] que fortalece costas e braços.",
      "Benefícios de incluir [tema] na rotina diária.",
      "Treino de [tema] que pode ser feito em 5 minutos.",
      "Como [tema] ajuda na saúde mental e foco.",
      "Treino de [tema] para aumentar flexibilidade rapidamente.",
      "Dicas de treino seguro de [tema] para iniciantes.",
      "Treino de [tema] que melhora coordenação e agilidade.",
      "Como [tema] ajuda a reduzir estresse e cansaço.",
      "Treino de [tema] em casa: fácil e eficiente.",
      "Exercícios de [tema] para fortalecer joelhos e tornozelos.",
      "Treino de [tema] para definição muscular em 4 semanas.",
      "Como [tema] ajuda a manter disciplina nos treinos.",
      "Treino de [tema] para melhorar resistência física geral.",
      "Dicas para evoluir nos treinos de [tema] rapidamente.",
      "Treino de [tema] que pode ser feito no escritório.",
      "Como [tema] melhora performance em treinos de corrida.",
      "Treino de [tema] para melhorar força explosiva.",
      "Benefícios do [tema] para saúde integral."
    ]
  }
};
