export const TEMPLATES = {
  fotografia: {
    post: [
      "Dicas para capturar [tema] de forma profissional 📸 #fotografia #dicas #photo",
      "Como [tema] transforma suas fotos em obras de arte 🎨 #fotografia #arte #photo",
      "Top 5 truques para fotos incríveis de [tema] 📸 #fotografia #truques #photo",
      "Antes e depois: veja como [tema] muda a composição 📷 #fotografia #antesedepois #photo",
      "Como [tema] melhora suas habilidades de enquadramento 📸 #fotografia #composicao #photo",
      "Novidades sobre técnicas de [tema] que você precisa conhecer 📰 #fotografia #tecnica #photo",
      "Dicas para iniciantes fotografarem [tema] 📷 #fotografia #iniciante #photo",
      "Como [tema] se tornou tendência entre fotógrafos 📸 #fotografia #tendencia #photo",
      "Análise completa de [tema] e suas técnicas 📷 #fotografia #analise #photo",
      "Como [tema] ajuda a capturar momentos especiais 📸 #fotografia #momentos #photo",
      "Top 10 erros que você deve evitar ao fotografar [tema] ⚠️ #fotografia #erros #photo",
      "Estratégias avançadas para capturar [tema] 📷 #fotografia #avancado #photo",
      "Como [tema] está revolucionando a fotografia 📸 #fotografia #inovacao #photo",
      "Truques secretos para fotos de [tema] que poucos conhecem 📷 #fotografia #segredos #photo",
      "Como [tema] ajuda a desenvolver percepção visual 📸 #fotografia #habilidades #photo",
      "Melhores equipamentos para fotografar [tema] 📷 #fotografia #equipamentos #photo",
      "Como fotografar [tema] em modo natural e espontâneo 📸 #fotografia #natural #photo",
      "Dicas de edição para fotos de [tema] 📷 #fotografia #edicao #photo",
      "Como [tema] mantém sua criatividade ativa 📸 #fotografia #criatividade #photo",
      "Fotografia competitiva: capture [tema] com perfeição 📷 #fotografia #competitivo #photo",
      "Como [tema] influencia tendências visuais 📸 #fotografia #tendencias #photo",
      "Top 5 ângulos para fotografar [tema] 📷 #fotografia #angulos #photo",
      "Como [tema] ajuda no desenvolvimento de atenção aos detalhes 📸 #fotografia #detalhes #photo",
      "Guia completo para iniciantes fotografarem [tema] 📷 #fotografia #guia #photo",
      "Como [tema] evoluiu com novas técnicas 📸 #fotografia #evolucao #photo",
      "Estratégias de iluminação para [tema] 📷 #fotografia #iluminacao #photo",
      "Como [tema] pode ser fotografado de forma casual 📸 #fotografia #casual #photo",
      "Dicas de lentes para capturar [tema] melhor 📷 #fotografia #lentes #photo",
      "Como [tema] se tornou viral entre fotógrafos 📸 #fotografia #viral #photo",
      "Fotografando [tema]: tudo o que você precisa saber 📷 #fotografia #tutorial #photo",
      "Como [tema] influencia a cultura visual 📸 #fotografia #cultura #photo",
      "Top 10 momentos épicos capturados com [tema] 📷 #fotografia #epico #photo",
      "Como [tema] é perfeito para ensaios longos 📸 #fotografia #ensaio #photo",
      "Dicas de equipamentos extras para fotografar [tema] 📷 #fotografia #setup #photo",
      "Como [tema] melhora trabalho em equipe em sessões 📸 #fotografia #cooperacao #photo",
      "Guia de composição e enquadramento para [tema] 📷 #fotografia #composicao #photo",
      "Como [tema] desafia sua criatividade 📸 #fotografia #criatividade #photo",
      "Melhores estratégias solo para fotografar [tema] 📷 #fotografia #solo #photo",
      "Como [tema] transforma sua experiência visual 📸 #fotografia #experiencia #photo",
      "Top 5 equipamentos para capturar [tema] 📷 #fotografia #equipamentos #photo",
      "Como [tema] melhora coordenação e foco 📸 #fotografia #habilidades #photo",
      "Dicas de eventos e workshops de [tema] 📷 #fotografia #eventos #photo",
      "Como fotografar [tema] em ambientes internos e externos 📸 #fotografia #ambiente #photo",
      "Guia de conquistas e exposições com [tema] 📷 #fotografia #exposicao #photo",
      "Como [tema] melhora pensamento estratégico de composição 📸 #fotografia #estrategia #photo",
      "Top 10 fotógrafos que dominam [tema] 📷 #fotografia #referencias #photo",
      "Como [tema] ajuda a socializar com outros fotógrafos 📸 #fotografia #comunidade #photo",
      "Dicas para fotógrafos iniciantes em [tema] 📷 #fotografia #iniciante #photo",
      "Como [tema] pode ser fotografado online e offline 📸 #fotografia #digital #photo",
      "Top 5 locais para capturar [tema] 📷 #fotografia #locais #photo",
      "Como [tema] desafia memória e percepção 📸 #fotografia #detalhes #photo",
      "Dicas de iluminação natural para [tema] 📷 #fotografia #luz #photo",
      "Como [tema] influencia tendências de edição 📸 #fotografia #edicao #photo",
      "Top 5 técnicas criativas com [tema] 📷 #fotografia #criatividade #photo",
      "Como [tema] mantém fotógrafos engajados 📸 #fotografia #engajamento #photo",
      "Estratégias de retrato em [tema] que funcionam 📷 #fotografia #retrato #photo",
      "Como [tema] melhora reflexos e observação 📸 #fotografia #habilidades #photo",
      "Dicas de edição avançada para [tema] 📷 #fotografia #avancado #photo",
      "Como [tema] pode ser capturado em família 📸 #fotografia #familia #photo",
      "Top 10 acessórios para fotografar [tema] 📷 #fotografia #acessorios #photo",
      "Como [tema] é ideal para desafios e competições 📸 #fotografia #competicao #photo",
      "Dicas de segurança e proteção do equipamento em [tema] 📷 #fotografia #seguranca #photo",
      "Como [tema] impacta a indústria da fotografia 📸 #fotografia #industria #photo",
      "Top 5 técnicas de edição para fotos de [tema] 📷 #fotografia #edicao #photo",
      "Como [tema] melhora multitarefa e planejamento 📸 #fotografia #habilidades #photo",
      "Dicas de eventos cooperativos de fotografia com [tema] 📷 #fotografia #workshop #photo",
      "Como [tema] mantém comunidade de fotógrafos ativa 📸 #fotografia #comunidade #photo",
      "Top 5 momentos divertidos ao fotografar [tema] 📷 #fotografia #humor #photo",
      "Como [tema] influencia influenciadores e fotógrafos digitais 📸 #fotografia #digital #photo",
      "Guia completo para explorar [tema] 📷 #fotografia #guia #photo",
      "Como [tema] ajuda a desenvolver pensamento crítico em fotografia 📸 #fotografia #estrategia #photo",
      "Dicas de equipamentos para melhorar desempenho em [tema] 📷 #fotografia #equipamentos #photo",
      "Como [tema] pode ser capturado sozinho ou em grupo 📸 #fotografia #solo #photo",
      "Top 5 truques avançados de fotografia com [tema] 📷 #fotografia #trucos #photo",
      "Como [tema] mantém diversão mesmo após longas sessões 📸 #fotografia #diversao #photo",
      "Dicas de eventos de temporada com [tema] 📷 #fotografia #eventos #photo",
      "Como [tema] é perfeito para fotógrafos iniciantes 📸 #fotografia #iniciante #photo",
      "Top 5 técnicas raras para capturar [tema] 📷 #fotografia #tecnica #photo",
      "Como [tema] ajuda a criar comunidade e amizade 📸 #fotografia #comunidade #photo",
      "Dicas de exibições e concursos com [tema] 📷 #fotografia #exposicao #photo",
      "Como [tema] evoluiu ao longo das atualizações de técnicas 📸 #fotografia #evolucao #photo",
      "Top 5 desafios fotográficos com [tema] 📷 #fotografia #desafios #photo",
      "Como [tema] mantém fotógrafos competitivos motivados 📸 #fotografia #competitivo #photo",
      "Dicas para engajar fãs e seguidores com [tema] 📷 #fotografia #engajamento #photo",
      "Como [tema] influencia a cultura visual mundial 📸 #fotografia #cultura #photo",
      "Top 5 estratégias para capturar [tema] perfeitamente 📷 #fotografia #estrategia #photo",
      "Como [tema] desafia suas habilidades de percepção visual 📸 #fotografia #habilidades #photo",
      "Dicas para eventos cooperativos com [tema] 📷 #fotografia #workshop #photo",
      "Como [tema] mantém a comunidade fiel por anos 📸 #fotografia #comunidade #photo",
      "Top 5 técnicas avançadas de captura em [tema] 📷 #fotografia #avancado #photo",
      "Como [tema] é perfeito para exposições online e físicas 📸 #fotografia #exposicao #photo",
      "Dicas de customização de imagens de [tema] 📷 #fotografia #customizacao #photo",
      "Como [tema] ajuda no desenvolvimento de paciência e foco 📸 #fotografia #habilidades #photo",
      "Top 5 momentos épicos capturados em [tema] 📷 #fotografia #epico #photo",
      "Como [tema] mantém fotógrafos desafiados continuamente 📸 #fotografia #desafios #photo",
      "Dicas de técnicas que melhoram experiência com [tema] 📷 #fotografia #tecnica #photo",
      "Como [tema] se tornou referência no mundo da fotografia 📸 #fotografia #referencia #photo"
    ]
  }
};
