export const TEMPLATES = {
  gaming: {
    post: [
      "Dicas para dominar [tema] e subir de nível 🎮 #gaming #dicas #games",
      "Como [tema] melhora sua estratégia nos jogos 🕹️ #gaming #estrategia #games",
      "Top 5 truques para arrasar em [tema] ⚡ #gaming #tricks #games",
      "Gameplay incrível de [tema] que você precisa ver 🎮 #gaming #gameplay #games",
      "Como [tema] ajuda a melhorar reflexos e coordenação 🕹️ #gaming #skills #games",
      "Novidades de [tema] que todos estão comentando 📰 #gaming #news #games",
      "Dicas para iniciantes em [tema] 🎮 #gaming #iniciante #games",
      "Como [tema] se tornou um sucesso entre gamers 🕹️ #gaming #popular #games",
      "Análise completa de [tema] e suas mecânicas 🎮 #gaming #review #games",
      "Como [tema] melhora a diversão com amigos 🕹️ #gaming #multiplayer #games",
      "Top 10 erros que você deve evitar em [tema] ⚠️ #gaming #dicas #games",
      "Estratégias avançadas para vencer em [tema] 🎮 #gaming #estrategia #games",
      "Como [tema] está revolucionando os eSports 🕹️ #gaming #esports #games",
      "Truques secretos em [tema] que poucos conhecem 🎮 #gaming #segredos #games",
      "Como [tema] aumenta suas habilidades de tomada de decisão 🕹️ #gaming #skills #games",
      "Melhores mods e add-ons para [tema] 🎮 #gaming #mods #games",
      "Como [tema] pode ser jogado em modo cooperativo 🕹️ #gaming #cooperativo #games",
      "Dicas de personalização de personagens em [tema] 🎮 #gaming #customizacao #games",
      "Como [tema] mantém você engajado por horas 🕹️ #gaming #diversao #games",
      "Jogos competitivos: domine [tema] com essas estratégias 🎮 #gaming #competitivo #games",
      "Como [tema] influencia a comunidade gamer 🕹️ #gaming #comunidade #games",
      "Top 5 builds para [tema] que garantem vitória 🎮 #gaming #builds #games",
      "Como [tema] melhora seu raciocínio rápido 🕹️ #gaming #habilidades #games",
      "Guia completo para iniciantes em [tema] 🎮 #gaming #guia #games",
      "Como [tema] evoluiu ao longo dos anos 🕹️ #gaming #historia #games",
      "Estratégias de equipe em [tema] que funcionam 🎮 #gaming #multiplayer #games",
      "Como [tema] pode ser jogado casualmente 🕹️ #gaming #casual #games",
      "Dicas de equipamentos para jogar [tema] melhor 🎮 #gaming #setup #games",
      "Como [tema] se tornou viral entre streamers 🕹️ #gaming #viral #games",
      "Jogabilidade em [tema]: o que você precisa saber 🎮 #gaming #gameplay #games",
      "Como [tema] influencia a cultura pop 🕹️ #gaming #cultura #games",
      "Top 10 momentos épicos em [tema] 🎮 #gaming #momentos #games",
      "Como [tema] é perfeito para maratonas de gameplay 🕹️ #gaming #maratona #games",
      "Dicas de upgrades e equipamentos em [tema] 🎮 #gaming #upgrades #games",
      "Como [tema] melhora habilidades de trabalho em equipe 🕹️ #gaming #cooperacao #games",
      "Guia de quests e missões em [tema] 🎮 #gaming #quests #games",
      "Como [tema] desafia sua criatividade 🕹️ #gaming #criatividade #games",
      "Melhores estratégias solo em [tema] 🎮 #gaming #solo #games",
      "Como [tema] transforma a experiência online 🕹️ #gaming #online #games",
      "Top 5 armas e equipamentos em [tema] 🎮 #gaming #armas #games",
      "Como [tema] ajuda na coordenação olho-mão 🕹️ #gaming #skills #games",
      "Dicas de eventos especiais em [tema] 🎮 #gaming #eventos #games",
      "Como [tema] pode ser jogado em modo competitivo 🕹️ #gaming #competitivo #games",
      "Guia de conquistas e troféus em [tema] 🎮 #gaming #conquistas #games",
      "Como [tema] melhora o pensamento estratégico 🕹️ #gaming #estrategia #games",
      "Top 10 personagens favoritos em [tema] 🎮 #gaming #personagens #games",
      "Como [tema] ajuda a socializar com outros jogadores 🕹️ #gaming #socializacao #games",
      "Dicas para streamers jogando [tema] 🎮 #gaming #streaming #games",
      "Como [tema] pode ser jogado offline e online 🕹️ #gaming #offlineonline #games",
      "Top 5 mapas e locais em [tema] 🎮 #gaming #mapas #games",
      "Como [tema] desafia sua memória e atenção 🕹️ #gaming #habilidades #games",
      "Dicas de combos e habilidades em [tema] 🎮 #gaming #combos #games",
      "Como [tema] influencia outros jogos e franquias 🕹️ #gaming #influencia #games",
      "Top 5 builds para iniciantes em [tema] 🎮 #gaming #builds #games",
      "Como [tema] mantém os jogadores engajados por meses 🕹️ #gaming #engajamento #games",
      "Estratégias de PvP em [tema] que funcionam 🎮 #gaming #pvp #games",
      "Como [tema] ajuda no desenvolvimento de reflexos rápidos 🕹️ #gaming #habilidades #games",
      "Dicas de personalização de skins em [tema] 🎮 #gaming #skins #games",
      "Como [tema] pode ser jogado em família 🕹️ #gaming #familia #games",
      "Top 10 mods que melhoram [tema] 🎮 #gaming #mods #games",
      "Como [tema] é ideal para desafios e torneios 🕹️ #gaming #torneios #games",
      "Dicas de segurança online em [tema] 🎮 #gaming #seguranca #games",
      "Como [tema] impacta a indústria de games 🕹️ #gaming #industria #games",
      "Top 5 estratégias de sobrevivência em [tema] 🎮 #gaming #sobrevivencia #games",
      "Como [tema] melhora suas habilidades multitarefa 🕹️ #gaming #skills #games",
      "Dicas para iniciantes em PvP de [tema] 🎮 #gaming #iniciante #games",
      "Como [tema] mantém sua comunidade ativa e engajada 🕹️ #gaming #comunidade #games",
      "Top 5 momentos engraçados em [tema] 🎮 #gaming #humor #games",
      "Como [tema] influencia streamers e YouTubers 🕹️ #gaming #streaming #games",
      "Guia completo para explorar [tema] 🎮 #gaming #guia #games",
      "Como [tema] ajuda a desenvolver pensamento crítico 🕹️ #gaming #estrategia #games",
      "Dicas de equipamentos para melhorar desempenho em [tema] 🎮 #gaming #setup #games",
      "Como [tema] pode ser jogado em grupo ou sozinho 🕹️ #gaming #multiplayer #games",
      "Top 5 hacks e dicas avançadas em [tema] 🎮 #gaming #dicas #games",
      "Como [tema] mantém a diversão mesmo após horas de jogo 🕹️ #gaming #diversao #games",
      "Dicas de eventos de temporada em [tema] 🎮 #gaming #eventos #games",
      "Como [tema] é perfeito para streamers iniciantes 🕹️ #gaming #streaming #games",
      "Top 5 armas e equipamentos raros em [tema] 🎮 #gaming #raridade #games",
      "Como [tema] ajuda a criar comunidade e amizade 🕹️ #gaming #comunidade #games",
      "Dicas de achievements e troféus em [tema] 🎮 #gaming #conquistas #games",
      "Como [tema] evoluiu ao longo das atualizações 🕹️ #gaming #atualizacoes #games",
      "Top 5 desafios em [tema] que você precisa completar 🎮 #gaming #desafios #games",
      "Como [tema] mantém jogadores competitivos motivados 🕹️ #gaming #competitivo #games",
      "Dicas de streaming para engajar fãs em [tema] 🎮 #gaming #streaming #games",
      "Como [tema] influencia a cultura gamer mundial 🕹️ #gaming #cultura #games",
      "Top 5 estratégias para vencer chefes em [tema] 🎮 #gaming #chefes #games",
      "Como [tema] desafia suas habilidades de raciocínio rápido 🕹️ #gaming #habilidades #games",
      "Dicas para eventos cooperativos em [tema] 🎮 #gaming #cooperativo #games",
      "Como [tema] mantém a comunidade fiel por anos 🕹️ #gaming #comunidade #games",
      "Top 5 builds competitivas em [tema] 🎮 #gaming #builds #games",
      "Como [tema] é perfeito para torneios online 🕹️ #gaming #torneios #games",
      "Dicas de customização de mapas em [tema] 🎮 #gaming #customizacao #games",
      "Como [tema] ajuda no desenvolvimento de paciência e estratégia 🕹️ #gaming #skills #games",
      "Top 5 momentos épicos capturados em [tema] 🎮 #gaming #epico #games",
      "Como [tema] mantém os jogadores desafiados continuamente 🕹️ #gaming #desafios #games",
      "Dicas de mods que melhoram experiência em [tema] 🎮 #gaming #mods #games",
      "Como [tema] se tornou referência no mundo gamer 🕹️ #gaming #referencia #games"
    ]
  }
};
