export const TEMPLATES = {
  marketingDigital: {
    post: [
      "Como [tema] pode aumentar suas vendas online 💻 3 passos rápidos para aplicar hoje! #marketingdigital #negocios #online",
      "Estratégia de marketing: use [tema] para engajar seu público. #marketingdigital #estrategia #socialmedia",
      "Dica rápida: [tema] é essencial para crescer online. #marketingdigital #crescimento #negocios",
      "Antes e depois: veja os resultados de aplicar [tema] em sua campanha! #marketingdigital #resultados #case",
      "Marketing digital eficiente: descubra como [tema] muda tudo. #marketingdigital #eficiencia #negocios",
      "Aumente o alcance usando [tema]. #marketingdigital #alcance #socialmedia",
      "Segredo de engajamento: [tema] aplicado corretamente. #marketingdigital #engajamento #estrategia",
      "Transforme sua estratégia com [tema]. #marketingdigital #estrategiadigital #negocios",
      "Use [tema] para gerar leads e vendas rapidamente. #marketingdigital #leads #vendas",
      "Descubra o poder do [tema] no marketing online. #marketingdigital #poder #estrategia",
      "Como [tema] pode aumentar a presença da sua marca online. #branding #marketingdigital #negocios",
      "3 maneiras de aplicar [tema] e crescer nas redes sociais. #socialmedia #marketingdigital #crescimento",
      "Dicas de marketing: aproveite [tema] para engajar mais. #marketingdigital #dicas #estrategia",
      "Como [tema] transforma visitantes em clientes. #marketingdigital #vendas #conversao",
      "Aumente suas vendas usando [tema] hoje mesmo. #marketingdigital #vendas #negocios",
      "Segredos para aplicar [tema] de forma estratégica. #marketingdigital #estrategia #sucesso",
      "Como [tema] ajuda a criar conteúdo viral. #marketingdigital #conteudo #viral",
      "Transforme suas campanhas com [tema]. #marketingdigital #campanhas #resultados",
      "Por que [tema] é essencial para negócios online. #marketingdigital #negocios #online",
      "Como [tema] pode melhorar seu engajamento no Instagram. #marketingdigital #instagram #engajamento",
      "5 formas de usar [tema] para impulsionar vendas. #marketingdigital #vendas #estrategia",
      "Como [tema] aumenta a autoridade da sua marca. #branding #marketingdigital #autoridade",
      "Dicas rápidas para aplicar [tema] agora. #marketingdigital #dicas #estrategia",
      "O impacto de [tema] no crescimento do seu negócio. #marketingdigital #crescimento #negocios",
      "Como [tema] ajuda a converter seguidores em clientes. #marketingdigital #conversao #socialmedia",
      "Estratégia prática usando [tema] para resultados rápidos. #marketingdigital #estrategia #resultados",
      "Como [tema] pode otimizar suas campanhas de anúncios. #marketingdigital #ads #negocios",
      "5 motivos para investir em [tema] no seu marketing. #marketingdigital #estrategia #negocios",
      "Transforme seu conteúdo com [tema]. #marketingdigital #conteudo #engajamento",
      "Como [tema] aumenta a fidelização de clientes. #marketingdigital #clientes #fidelizacao",
      "Segredos de marketing: [tema] que você precisa conhecer. #marketingdigital #segredos #estrategia",
      "Como [tema] ajuda a criar campanhas de sucesso. #marketingdigital #campanhas #sucesso",
      "Dicas para melhorar sua presença online usando [tema]. #marketingdigital #presenca #online",
      "Como [tema] pode gerar leads qualificados. #marketingdigital #leads #vendas",
      "Estratégias de marketing usando [tema] para pequenas empresas. #marketingdigital #negocios #estrategia",
      "Como [tema] aumenta o tráfego do seu site. #marketingdigital #trafego #online",
      "Dicas de engajamento: aplique [tema] nas suas redes sociais. #marketingdigital #engajamento #socialmedia",
      "Como [tema] melhora a comunicação com seus clientes. #marketingdigital #clientes #comunicacao",
      "5 passos para aplicar [tema] e aumentar vendas. #marketingdigital #vendas #estrategia",
      "Como usar [tema] para criar conteúdo envolvente. #marketingdigital #conteudo #engajamento",
      "O impacto de [tema] na conversão de leads. #marketingdigital #conversao #negocios",
      "Como [tema] ajuda a construir autoridade online. #marketingdigital #autoridade #branding",
      "Transforme suas campanhas pagas com [tema]. #marketingdigital #ads #resultados",
      "Como [tema] otimiza suas estratégias de marketing. #marketingdigital #estrategia #sucesso",
      "Dicas práticas: aplique [tema] e veja resultados rápidos. #marketingdigital #dicas #negocios",
      "Como [tema] ajuda a criar campanhas memoráveis. #marketingdigital #campanhas #criatividade",
      "Estratégias para aumentar vendas usando [tema]. #marketingdigital #vendas #estrategia",
      "Como [tema] melhora o engajamento no TikTok. #marketingdigital #tiktok #engajamento",
      "Dicas de marketing de conteúdo com [tema]. #marketingdigital #conteudo #estrategia",
      "Como [tema] pode impulsionar seu negócio online. #marketingdigital #negocios #online",
      "5 motivos para aplicar [tema] na sua estratégia digital. #marketingdigital #estrategia #sucesso",
      "Como [tema] gera tráfego orgânico para seu site. #marketingdigital #trafego #seo",
      "Estratégias de social media usando [tema]. #marketingdigital #socialmedia #estrategia",
      "Como [tema] aumenta a retenção de clientes. #marketingdigital #clientes #fidelizacao",
      "Dicas rápidas para criar campanhas de sucesso com [tema]. #marketingdigital #campanhas #sucesso",
      "Como [tema] ajuda a criar conteúdo compartilhável. #marketingdigital #conteudo #viral",
      "Estratégias avançadas usando [tema] para resultados incríveis. #marketingdigital #estrategia #resultados",
      "Como [tema] pode otimizar anúncios pagos. #marketingdigital #ads #vendas",
      "Dicas para engajar mais clientes usando [tema]. #marketingdigital #engajamento #clientes",
      "Como [tema] melhora suas métricas de marketing digital. #marketingdigital #metricas #sucesso",
      "Como usar [tema] para campanhas de email marketing. #marketingdigital #emailmarketing #estrategia",
      "Estratégias criativas com [tema] para crescer online. #marketingdigital #criatividade #negocios",
      "Como [tema] ajuda a aumentar seguidores nas redes sociais. #marketingdigital #socialmedia #crescimento",
      "Dicas de marketing digital: [tema] para iniciantes. #marketingdigital #dicas #estrategia",
      "Como [tema] otimiza funis de vendas. #marketingdigital #funildevendas #vendas",
      "5 formas de aplicar [tema] e gerar resultados imediatos. #marketingdigital #estrategia #resultados",
      "Como [tema] melhora a performance de suas campanhas. #marketingdigital #performance #ads",
      "Estratégias de conteúdo usando [tema] para engajar. #marketingdigital #conteudo #engajamento",
      "Como [tema] ajuda a criar anúncios que convertem. #marketingdigital #ads #conversao",
      "Dicas avançadas: maximize o potencial de [tema]. #marketingdigital #estrategia #negocios",
      "Como [tema] transforma suas redes sociais em máquinas de vendas. #marketingdigital #socialmedia #vendas",
      "Como usar [tema] para campanhas de storytelling. #marketingdigital #storytelling #conteudo",
      "Estratégias de marketing de performance com [tema]. #marketingdigital #performance #resultados",
      "Como [tema] ajuda a engajar leads frios. #marketingdigital #leads #engajamento",
      "Dicas para otimizar campanhas com [tema]. #marketingdigital #ads #estrategia",
      "Como [tema] gera resultados consistentes no marketing digital. #marketingdigital #resultados #negocios",
      "Estratégias de growth marketing usando [tema]. #marketingdigital #growth #estrategia",
      "Como [tema] ajuda a aumentar conversões em e-commerce. #marketingdigital #conversao #ecommerce",
      "Dicas práticas para aplicar [tema] e gerar engajamento. #marketingdigital #engajamento #conteudo",
      "Como usar [tema] para criar campanhas omnichannel. #marketingdigital #omnichannel #estrategia",
      "Estratégias de branding usando [tema]. #marketingdigital #branding #negocios",
      "Como [tema] melhora o ROI de suas campanhas. #marketingdigital #ROI #ads",
      "Dicas rápidas para maximizar resultados com [tema]. #marketingdigital #resultados #estrategia",
      "Como [tema] transforma leads em clientes fiéis. #marketingdigital #leads #fidelizacao",
      "Estratégias de social selling usando [tema]. #marketingdigital #socialselling #vendas",
      "Como [tema] aumenta o engajamento orgânico. #marketingdigital #engajamento #socialmedia",
      "Dicas de marketing de conteúdo: [tema] para negócios. #marketingdigital #conteudo #negocios",
      "Como [tema] ajuda a criar funis de vendas eficientes. #marketingdigital #funildevendas #estrategia",
      "Estratégias de SEO usando [tema]. #marketingdigital #seo #estrategia",
      "Como [tema] pode otimizar campanhas de tráfego pago. #marketingdigital #ads #trafego",
      "Dicas avançadas de marketing digital: [tema]. #marketingdigital #estrategia #sucesso",
      "Como usar [tema] para melhorar a experiência do cliente. #marketingdigital #clientes #experiencia",
      "Estratégias de marketing de conteúdo viral com [tema]. #marketingdigital #conteudo #viral"
    ]
  }
};


