export const TEMPLATES = {
  moda: {
    post: [
      "5 tendências de [tema] que você precisa conhecer nesta temporada 👗 #moda #fashion #tendencias",
      "Como usar [tema] para arrasar em qualquer look 💃 #estilo #modafeminina",
      "Dicas de [tema] para montar looks incríveis no dia a dia 🌟 #fashiontips #moda",
      "Transforme seu guarda-roupa com [tema] e esteja sempre na moda 👚 #style #moda",
      "Como combinar [tema] com acessórios para looks perfeitos 👜 #fashion #lookdodia",
      "Segredos de estilo: use [tema] e destaque-se na multidão ✨ #moda #fashionstyle",
      "Inspire-se com looks de [tema] que estão bombando nas redes sociais 📸 #fashioninspo #moda",
      "Como adaptar [tema] ao seu estilo pessoal 🧥 #estilo #fashiontips",
      "Top 5 combinações de [tema] para arrasar em festas 🎉 #lookdodia #modafashion",
      "Dicas de [tema] para se sentir confiante e elegante 👠 #fashiontips #moda",
      "Como [tema] pode transformar seu visual em minutos ⏱️ #modafeminina #fashion",
      "Looks casuais com [tema] para o dia a dia 👖 #fashionstyle #moda",
      "Como [tema] ajuda a criar combinações versáteis e estilosas 👕 #moda #estilo",
      "Top peças de [tema] que toda fashionista deve ter 👗 #fashiontips #moda",
      "Como usar [tema] sem perder o conforto e o estilo 🌿 #fashionstyle #moda",
      "Inspire-se em celebridades que amam [tema] 📸 #moda #fashioninspo",
      "Dicas de [tema] para arrasar em eventos especiais 💫 #fashiontips #lookdodia",
      "Como transformar seu visual usando apenas [tema] 🔝 #modafeminina #fashion",
      "Tendências de [tema] que estarão em alta nesta estação 🌸 #moda #fashiontrends",
      "Como escolher o [tema] ideal para cada ocasião 🎯 #estilo #modafashion",
      "Top 10 combinações de cores com [tema] que funcionam sempre 🎨 #fashiontips #moda",
      "Como adaptar [tema] ao seu tipo de corpo 👗 #fashionstyle #modafeminina",
      "Dicas de acessórios que combinam com [tema] 👜 #fashiontips #lookdodia",
      "Como usar [tema] no trabalho sem perder a elegância 👔 #moda #estilo",
      "Looks de verão com [tema] para arrasar na estação ☀️ #fashion #modafeminina",
      "Como transformar [tema] básico em look fashionista 🌟 #moda #fashionstyle",
      "Top 5 erros ao usar [tema] e como evitá-los ❌ #fashiontips #moda",
      "Como [tema] pode valorizar sua silhueta e estilo 💃 #modafeminina #fashion",
      "Dicas de compras: como escolher o melhor [tema] 🛍️ #fashiontips #moda",
      "Como combinar [tema] com peças clássicas e modernas 👕 #estilo #modafashion",
      "Top 5 looks com [tema] para arrasar em fotos 📸 #fashionstyle #moda",
      "Como usar [tema] no inverno sem perder o estilo ❄️ #moda #fashiontips",
      "Inspirações de looks com [tema] para diferentes ocasiões 🎉 #fashioninspo #moda",
      "Como [tema] ajuda a criar looks elegantes e sofisticados 💎 #modafeminina #fashion",
      "Dicas de styling: combinar [tema] com estampas e cores 🎨 #fashiontips #moda",
      "Como adaptar [tema] a diferentes estilos pessoais 👗 #fashionstyle #moda",
      "Top 5 formas de usar [tema] para looks casuais e chiques 🌟 #fashiontips #moda",
      "Como [tema] pode ser usado em roupas de festa e eventos especiais 💃 #moda #fashionstyle",
      "Dicas de looks minimalistas usando [tema] 🌿 #fashion #estilo",
      "Como usar [tema] sem cometer erros de moda comuns ❌ #fashiontips #moda",
      "Tendências de [tema] que nunca saem de moda 🔝 #moda #fashioninspo",
      "Como combinar [tema] com sapatos e bolsas 👠👜 #fashionstyle #moda",
      "Top peças-chave de [tema] para montar seu guarda-roupa 🛍️ #fashiontips #moda",
      "Como usar [tema] de forma criativa em diferentes estações 🌸❄️ #moda #fashionstyle",
      "Looks de festa com [tema] que vão te deixar elegante ✨ #fashioninspo #moda",
      "Como [tema] ajuda a criar combinações modernas e ousadas 🌟 #fashiontips #moda",
      "Dicas de [tema] para looks de trabalho e eventos profissionais 👔 #fashionstyle #modafeminina",
      "Como adaptar [tema] para looks descontraídos de fim de semana 🏖️ #fashion #moda",
      "Top 5 maneiras de combinar [tema] com acessórios statement 💎 #fashiontips #moda",
      "Como usar [tema] sem perder a sua identidade de estilo 🌈 #moda #fashionstyle",
      "Inspirações de street style usando [tema] 📸 #fashioninspo #moda",
      "Como [tema] pode valorizar seu estilo pessoal e confiança 💃 #modafeminina #fashion",
      "Dicas de looks monocromáticos usando [tema] 🎨 #fashiontips #moda",
      "Como combinar [tema] com tendências atuais sem exageros 🔝 #fashionstyle #moda",
      "Top 5 ideias de looks para eventos noturnos com [tema] 🌙 #fashion #modafeminina",
      "Como usar [tema] em diferentes tipos de tecidos e texturas 🧵 #fashiontips #moda",
      "Looks de verão com [tema] que são práticos e estilosos ☀️ #fashionstyle #moda",
      "Como adaptar [tema] para diferentes ocasiões formais e informais 👗 #fashion #modafeminina",
      "Dicas de combinação de cores com [tema] que funcionam sempre 🎨 #fashiontips #moda",
      "Como [tema] ajuda a criar looks elegantes para todas as idades 🌟 #fashionstyle #moda",
      "Top 5 maneiras de transformar um look básico com [tema] ✨ #fashiontips #moda",
      "Como usar [tema] de forma criativa em acessórios e detalhes 💎 #fashionstyle #moda",
      "Dicas de looks comfy com [tema] para o dia a dia 🌿 #fashion #modafeminina",
      "Como combinar [tema] com estampas sem perder o estilo 🖤 #fashiontips #moda",
      "Top 5 erros comuns ao usar [tema] e como evitá-los ❌ #fashionstyle #moda",
      "Como usar [tema] em looks de trabalho e happy hour 👔🍸 #moda #fashiontips",
      "Inspirações de looks minimalistas usando [tema] 🌿 #fashionstyle #moda",
      "Como [tema] pode ser usado em roupas de festa e eventos especiais 💫 #fashiontips #moda",
      "Top 5 looks com [tema] que combinam com sapatos e bolsas 👠👜 #fashionstyle #moda",
      "Como adaptar [tema] a diferentes estilos pessoais e estações 🌸❄️ #moda #fashiontips",
      "Dicas de looks elegantes usando [tema] para casamentos e formaturas 💍 #fashionstyle #moda",
      "Como combinar [tema] com acessórios discretos ou statement 💎 #fashiontips #moda",
      "Top 5 tendências de [tema] que você não pode deixar de usar 🔝 #fashionstyle #moda",
      "Como usar [tema] para looks casuais e confortáveis 🏖️ #fashion #modafeminina",
      "Dicas de street style com [tema] para arrasar nas fotos 📸 #fashionstyle #moda",
      "Como [tema] pode ser usado em sobreposições e camadas sem erro 🧥 #fashiontips #moda",
      "Top 5 maneiras de combinar [tema] com peças básicas do guarda-roupa 👕 #fashionstyle #moda",
      "Como usar [tema] em looks de inverno sem perder o estilo ❄️ #moda #fashiontips",
      "Dicas de styling para usar [tema] em looks de verão e primavera ☀️🌸 #fashionstyle #moda",
      "Como [tema] ajuda a criar looks modernos e elegantes sem esforço 🌟 #fashiontips #moda",
      "Top 5 acessórios que combinam com [tema] e elevam o look 💎 #fashionstyle #moda",
      "Como usar [tema] para criar combinações ousadas e criativas 🎨 #moda #fashiontips",
      "Inspirações de looks do dia a dia com [tema] que são fáceis de reproduzir 🌿 #fashionstyle #moda",
      "Como [tema] transforma um look básico em fashionista 💃 #fashiontips #moda",
      "Top 5 ideias de looks para trabalhar com [tema] e estilo 👔 #fashionstyle #moda",
      "Como usar [tema] sem medo de errar na combinação de cores 🎨 #fashiontips #moda",
      "Dicas de styling com [tema] para todas as ocasiões 🌟 #fashionstyle #moda",
      "Como [tema] ajuda a criar looks versáteis e funcionais para o dia a dia 👜 #fashiontips #moda",
      "Top 5 peças-chave de [tema] para ter sempre no armário 👗 #fashionstyle #moda",
      "Como usar [tema] de forma criativa em diferentes tipos de roupas e acessórios 💎 #fashiontips #moda",
      "Dicas para adaptar [tema] ao seu estilo pessoal e tendências atuais 🌸 #fashionstyle #moda",
      "Como [tema] transforma seu visual e aumenta sua confiança 💃 #fashiontips #moda",
      "Top 5 combinações de [tema] com cores neutras que funcionam sempre 🎨 #fashionstyle #moda",
      "Como usar [tema] em looks sofisticados para festas e eventos especiais ✨ #fashiontips #moda",
      "Dicas de looks confortáveis com [tema] para o dia a dia 🌿 #fashionstyle #moda"
    ]
  }
};
