export const TEMPLATES = {
  pets: {
    post: [
      "Dicas de cuidados com [tema] para deixar seu pet feliz 🐶 #pets #cuidados #animais",
      "Como [tema] pode melhorar a vida do seu pet 🐾 #pets #amor #animais",
      "Brincadeiras divertidas com [tema] 🐕 #pets #diversao #cachorros",
      "Alimentação saudável para [tema] 🍖 #pets #alimentacao #animais",
      "Treinamento fácil para [tema] 🐾 #pets #treinamento #cachorros",
      "Como [tema] ajuda no bem-estar do seu animal 🐶 #pets #saude #animais",
      "Os melhores brinquedos para [tema] 🐾 #pets #diversao #brinquedos",
      "Dicas de higiene para [tema] 🛁 #pets #higiene #cuidados",
      "Como [tema] interage com outros animais 🐕🐾 #pets #amizade #animais",
      "Passeios seguros com [tema] 🚶‍♂️ #pets #passeios #cachorros",
      "Cuidados com a saúde de [tema] 🏥 #pets #saude #veterinario",
      "Como escolher o melhor alimento para [tema] 🍽️ #pets #alimentacao #animais",
      "Dicas de adestramento para [tema] 🐾 #pets #treinamento #educacao",
      "Como [tema] melhora a felicidade da sua família 🏡 #pets #amor #animais",
      "Atividades físicas para [tema] 🐕 #pets #atividade #saude",
      "Como [tema] se adapta ao ambiente da sua casa 🏠 #pets #adaptacao #animais",
      "Os melhores acessórios para [tema] 🐾 #pets #acessorios #animais",
      "Como [tema] se comporta com crianças 👶 #pets #criancas #amizade",
      "Dicas para viagens com [tema] ✈️ #pets #viagem #animais",
      "Como [tema] ajuda a reduzir o estresse 🐶 #pets #bemestar #saude",
      "Melhores rações para [tema] 🥩 #pets #alimentacao #cachorros",
      "Como [tema] aprende truques facilmente 🐾 #pets #treinamento #truques",
      "Brincadeiras caseiras para [tema] 🏡 #pets #diversao #animais",
      "Como [tema] se comunica com humanos 🐶 #pets #comunicacao #animais",
      "Cuidados com filhotes de [tema] 🐾 #pets #filhotes #cuidados",
      "Como manter [tema] ativo e saudável 🏃‍♂️ #pets #atividade #saude",
      "Os melhores locais para passear com [tema] 🌳 #pets #passeio #animais",
      "Como [tema] se relaciona com outros pets 🐶🐾 #pets #amizade #cachorros",
      "Dicas de grooming para [tema] ✂️ #pets #higiene #cuidados",
      "Como [tema] se comporta em diferentes estações 🌞❄️ #pets #clima #animais",
      "Atividades mentais para [tema] 🧠 #pets #mente #diversao",
      "Como [tema] ajuda na socialização da família 👨‍👩‍👧‍👦 #pets #familia #amor",
      "Melhores acessórios de passeio para [tema] 🐾 #pets #acessorios #passeio",
      "Como [tema] reage a novos ambientes 🏠 #pets #adaptacao #animais",
      "Dicas de saúde preventiva para [tema] 🏥 #pets #saude #prevencao",
      "Como [tema] se diverte em casa 🏡 #pets #diversao #animais",
      "Cuidados especiais para [tema] idosos 🐕 #pets #idosos #cuidados",
      "Como [tema] ajuda na educação de crianças 👶 #pets #educacao #amizade",
      "Brincadeiras interativas para [tema] 🐾 #pets #interacao #animais",
      "Como [tema] se mantém feliz e saudável 🐶 #pets #saude #bemestar",
      "Dicas de alimentação natural para [tema] 🥩 #pets #alimentacao #saude",
      "Como [tema] aprende comandos básicos 🐾 #pets #treinamento #educacao",
      "Passeios de aventura com [tema] 🌄 #pets #aventura #diversao",
      "Como [tema] se adapta à vida urbana 🏙️ #pets #adaptacao #animais",
      "Os melhores brinquedos educativos para [tema] 🧸 #pets #educativo #animais",
      "Como [tema] ajuda na felicidade diária 🐶 #pets #amor #bemestar",
      "Dicas de higiene dental para [tema] 🦷 #pets #saude #higiene",
      "Como [tema] se comporta em festas e eventos 🎉 #pets #comportamento #animais",
      "Treinamento avançado para [tema] 🐾 #pets #treinamento #educacao",
      "Como [tema] se diverte no quintal 🏡 #pets #diversao #animais",
      "Dicas de segurança para [tema] em casa 🏠 #pets #seguranca #cuidados",
      "Como [tema] aprende truques criativos 🐶 #pets #truques #educacao",
      "Passeios de carro com [tema] 🚗 #pets #viagem #animais",
      "Como [tema] interage com outros animais da vizinhança 🐕🐾 #pets #amizade #animais",
      "Dicas de primeiros socorros para [tema] 🏥 #pets #saude #primeirossocorros",
      "Como [tema] se comporta durante tempestades ⛈️ #pets #comportamento #seguranca",
      "Os melhores snacks para [tema] 🥓 #pets #alimentacao #diversao",
      "Como [tema] ajuda na redução de ansiedade 🐶 #pets #bemestar #saude",
      "Brincadeiras ao ar livre com [tema] 🌳 #pets #diversao #atividade",
      "Como [tema] se mantém ativo em dias de chuva ☔ #pets #atividade #animais",
      "Dicas de treino de agilidade para [tema] 🐾 #pets #treinamento #diversao",
      "Como [tema] se comporta com novos membros da família 👨‍👩‍👧‍👦 #pets #adaptacao #familia",
      "Passeios matinais com [tema] 🌅 #pets #atividade #passeio",
      "Como [tema] se diverte com outros pets 🐶🐾 #pets #socializacao #animais",
      "Dicas de cuidados com pelo e pele de [tema] 🛁 #pets #higiene #cuidados",
      "Como [tema] aprende novos comandos rapidamente 🐾 #pets #educacao #treinamento",
      "Atividades de enriquecimento ambiental para [tema] 🌿 #pets #diversao #saude",
      "Como [tema] reage a brinquedos interativos 🧸 #pets #diversao #animais",
      "Dicas para viagens longas com [tema] 🚗 #pets #viagem #seguranca",
      "Como [tema] se comporta em clínicas veterinárias 🏥 #pets #saude #comportamento",
      "Melhores exercícios físicos para [tema] 🐕 #pets #atividade #saude",
      "Como [tema] ajuda a melhorar a rotina diária 🏡 #pets #bemestar #amor",
      "Dicas de alimentação equilibrada para [tema] 🍖 #pets #alimentacao #saude",
      "Como [tema] interage com brinquedos educativos 🧸 #pets #educacao #diversao",
      "Passeios noturnos seguros com [tema] 🌙 #pets #passeios #seguranca",
      "Como [tema] se comporta em festas de animais 🐶🎉 #pets #socializacao #animais",
      "Treinamento de comandos avançados para [tema] 🐾 #pets #educacao #treinamento",
      "Como [tema] se mantém saudável na terceira idade 🐕 #pets #idosos #saude",
      "Brincadeiras aquáticas com [tema] 🏊 #pets #diversao #agua",
      "Como [tema] se adapta a novos ambientes 🏡 #pets #adaptacao #animais",
      "Dicas de brinquedos DIY para [tema] 🧸 #pets #criatividade #diversao",
      "Como [tema] ajuda na socialização de outros pets 🐶🐾 #pets #socializacao #amor",
      "Cuidados com unhas e patas de [tema] ✂️ #pets #cuidados #saude",
      "Como [tema] aprende comandos básicos de obediência 🐾 #pets #educacao #treinamento",
      "Passeios de bicicleta com [tema] 🚴 #pets #atividade #diversao",
      "Como [tema] se comporta em encontros com outros animais 🐕🐾 #pets #socializacao #animais",
      "Dicas de saúde mental para [tema] 🐶 #pets #bemestar #saude",
      "Como [tema] se diverte em parques para pets 🌳 #pets #diversao #atividade",
      "Brincadeiras mentais para [tema] 🧠 #pets #menteforte #educacao",
      "Como [tema] ajuda na interação familiar 🏡 #pets #familia #amor",
      "Cuidados especiais com filhotes de [tema] 🐾 #pets #filhotes #cuidados",
      "Como [tema] se adapta a novos brinquedos 🧸 #pets #diversao #adaptacao",
      "Dicas de grooming avançado para [tema] ✂️ #pets #higiene #cuidados",
      "Como [tema] se mantém saudável e ativo 🐶 #pets #atividade #saude",
      "Brincadeiras criativas para [tema] em casa 🏡 #pets #diversao #criatividade",
      "Como [tema] ajuda a reduzir o estresse da família 🐾 #pets #bemestar #amor",
      "Passeios em trilhas com [tema] 🌄 #pets #aventura #atividade",
      "Como [tema] interage com crianças e adultos 👶👨‍👩‍👧‍👦 #pets #socializacao #familia",
      "Dicas de alimentação especial para [tema] 🥩 #pets #alimentacao #saude"
    ]
  }
};
