export const TEMPLATES = {
  saude: {
    post: [
      "5 hábitos essenciais para melhorar [tema] diariamente 🏥 #saude #bemestar #qualidadedevida",
      "Como manter [tema] em equilíbrio 💪 #saude #vidaSaudavel #bemestar",
      "Dicas práticas para cuidar da [tema] todos os dias 🌿 #saude #dicas #saudavel",
      "Exercícios simples para melhorar [tema] 🏃‍♂️ #saude #fitness #bemestar",
      "Alimentos que ajudam a fortalecer [tema] 🥗 #saude #alimentacaosaudavel #nutricao",
      "Como prevenir problemas relacionados à [tema] ⚕️ #saude #prevencao #bemestar",
      "Rotina diária para manter [tema] em dia ⏰ #saude #habitos #bemestar",
      "Dicas de especialistas para melhorar [tema] 👩‍⚕️ #saude #saudemental #bemestar",
      "Como o sono influencia [tema] 😴 #saude #qualidadedesono #bemestar",
      "Técnicas de relaxamento para melhorar [tema] 🧘 #saude #relaxamento #bemestar",
      "Importância da hidratação para [tema] 💧 #saude #hidratacao #bemestar",
      "Como lidar com estresse para proteger [tema] 😌 #saude #stress #bemestar",
      "Dicas para manter [tema] saudável na rotina diária 🏋️ #saude #fitness #bemestar",
      "Alimentos que prejudicam [tema] ❌ #saude #nutricao #bemestar",
      "Como a meditação pode melhorar [tema] 🧘‍♂️ #saude #meditacao #bemestar",
      "Riscos de negligenciar [tema] ⚠️ #saude #prevencao #bemestar",
      "Como a atividade física impacta [tema] 🏃‍♀️ #saude #exercicio #fitness",
      "Alimentos naturais que fortalecem [tema] 🍎 #saude #nutricao #bemestar",
      "Como manter [tema] em equilíbrio emocional 🧠 #saude #saudemental #bemestar",
      "Importância de consultas regulares para [tema] 🏥 #saude #prevencao #bemestar",
      "Como evitar doenças relacionadas a [tema] 🛡️ #saude #prevencao #bemestar",
      "Dicas de hábitos saudáveis para proteger [tema] 🌿 #saude #habitos #bemestar",
      "Como reduzir inflamações e proteger [tema] 🔥 #saude #bemestar #saudavel",
      "Rotina matinal para melhorar [tema] 🌅 #saude #bemestar #habitos",
      "Benefícios de caminhar para [tema] 🚶 #saude #fitness #bemestar",
      "Como manter [tema] saudável mesmo com a correria diária ⏳ #saude #bemestar #habitos",
      "Dicas de alimentação equilibrada para [tema] 🥦 #saude #nutricao #bemestar",
      "Como o estresse afeta [tema] 😟 #saude #saudemental #bemestar",
      "Técnicas de respiração para melhorar [tema] 🌬️ #saude #relaxamento #bemestar",
      "Importância do check-up regular para [tema] 🩺 #saude #prevencao #bemestar",
      "Como fortalecer [tema] de forma natural 🌱 #saude #bemestar #saudavel",
      "Atividades físicas recomendadas para [tema] 🏋️ #saude #fitness #bemestar",
      "Como a postura influencia [tema] 🪑 #saude #postura #bemestar",
      "Dicas de mindfulness para melhorar [tema] 🧘‍♀️ #saude #mindfulness #bemestar",
      "Benefícios do sol para [tema] ☀️ #saude #vitaminaD #bemestar",
      "Como lidar com ansiedade e proteger [tema] 😌 #saude #ansiedade #bemestar",
      "Riscos do sedentarismo para [tema] ⚠️ #saude #atividadefisica #bemestar",
      "Alimentos que ajudam a reduzir o colesterol e proteger [tema] 🥑 #saude #nutricao #bemestar",
      "Como melhorar [tema] com exercícios respiratórios 🌬️ #saude #respiracao #bemestar",
      "Dicas para manter [tema] saudável durante viagens ✈️ #saude #bemestar #viagem",
      "Como organizar a rotina para proteger [tema] ⏰ #saude #habitos #bemestar",
      "Benefícios de atividades ao ar livre para [tema] 🌳 #saude #natureza #bemestar",
      "Como a música pode melhorar [tema] 🎶 #saude #bemestar #saudemental",
      "Dicas de alongamento para proteger [tema] 🤸‍♂️ #saude #fitness #bemestar",
      "Como o consumo de água impacta [tema] 💧 #saude #hidratacao #bemestar",
      "Alimentos ricos em antioxidantes para [tema] 🫐 #saude #nutricao #bemestar",
      "Como a meditação diária melhora [tema] 🧘 #saude #bemestar #saudemental",
      "Rotina de autocuidado para proteger [tema] 🛁 #saude #autocuidado #bemestar",
      "Dicas para controlar pressão arterial e proteger [tema] ❤️ #saude #bemestar #prevencao",
      "Como reduzir o consumo de açúcar para melhorar [tema] 🍭 #saude #nutricao #bemestar",
      "Exercícios de fortalecimento para proteger [tema] 💪 #saude #fitness #bemestar",
      "Como evitar lesões e cuidar de [tema] 🩹 #saude #prevenção #bemestar",
      "Alimentos que fortalecem o sistema imunológico e [tema] 🥦 #saude #nutricao #bemestar",
      "Como dormir melhor para melhorar [tema] 😴 #saude #sono #bemestar",
      "Dicas de suplementos naturais para [tema] 🌿 #saude #nutricao #bemestar",
      "Como lidar com a ansiedade e proteger [tema] 🧠 #saude #saudemental #bemestar",
      "Rotina de exercícios leves para [tema] 🏃‍♂️ #saude #fitness #bemestar",
      "Como manter [tema] saudável com alimentação equilibrada 🥗 #saude #nutricao #bemestar",
      "Benefícios da caminhada diária para [tema] 🚶‍♀️ #saude #fitness #bemestar",
      "Como reduzir inflamações e proteger [tema] 🔥 #saude #bemestar #saudavel",
      "Dicas para proteger [tema] durante mudanças de estação 🍂 #saude #bemestar #prevencao",
      "Como o yoga ajuda a melhorar [tema] 🧘‍♂️ #saude #yoga #bemestar",
      "Rotina de hábitos saudáveis para [tema] 🌿 #saude #habitos #bemestar",
      "Como prevenir doenças crônicas e proteger [tema] ⚠️ #saude #prevencao #bemestar",
      "Dicas para cuidar de [tema] durante a rotina de trabalho 💻 #saude #bemestar #habitos",
      "Como manter [tema] em equilíbrio emocional 🧠 #saude #saudemental #bemestar",
      "Alimentos que reduzem o estresse e ajudam [tema] 🥑 #saude #nutricao #bemestar",
      "Como organizar a alimentação para fortalecer [tema] 🍎 #saude #nutricao #bemestar",
      "Exercícios de alongamento diário para proteger [tema] 🤸‍♀️ #saude #fitness #bemestar",
      "Como a respiração profunda ajuda a melhorar [tema] 🌬️ #saude #relaxamento #bemestar",
      "Rotina matinal saudável para proteger [tema] 🌅 #saude #habitos #bemestar",
      "Como a atividade física regular melhora [tema] 🏋️ #saude #fitness #bemestar",
      "Dicas para manter [tema] saudável durante viagens ✈️ #saude #bemestar #viagem",
      "Como lidar com a pressão do dia a dia e proteger [tema] 😌 #saude #stress #bemestar",
      "Alimentos anti-inflamatórios para [tema] 🥗 #saude #nutricao #bemestar",
      "Como o consumo de frutas impacta [tema] 🍎 #saude #nutricao #bemestar",
      "Benefícios do alongamento diário para [tema] 🤸 #saude #fitness #bemestar",
      "Como manter [tema] saudável com exercícios em casa 🏠 #saude #fitness #bemestar",
      "Rotina de autocuidado e bem-estar para [tema] 🛁 #saude #autocuidado #bemestar",
      "Como reduzir ansiedade e melhorar [tema] 🧘 #saude #saudemental #bemestar",
      "Dicas de alimentação saudável para fortalecer [tema] 🥦 #saude #nutricao #bemestar",
      "Como manter [tema] em equilíbrio durante mudanças de rotina ⏰ #saude #habitos #bemestar",
      "Benefícios de exercícios aeróbicos para [tema] 🏃‍♀️ #saude #fitness #bemestar",
      "Como a hidratação correta ajuda a melhorar [tema] 💧 #saude #hidratacao #bemestar",
      "Rotina de mindfulness para cuidar de [tema] 🧘‍♀️ #saude #mindfulness #bemestar",
      "Como a alimentação balanceada protege [tema] 🥗 #saude #nutricao #bemestar",
      "Dicas de suplementos naturais para melhorar [tema] 🌿 #saude #bemestar #nutricao",
      "Como o exercício físico regular protege [tema] 🏋️‍♂️ #saude #fitness #bemestar",
      "Riscos de negligenciar [tema] ⚠️ #saude #prevencao #bemestar",
      "Como melhorar [tema] com pequenas mudanças diárias 🕒 #saude #habitos #bemestar",
      "Benefícios da caminhada matinal para [tema] 🚶‍♂️ #saude #fitness #bemestar",
      "Como organizar refeições para proteger [tema] 🍴 #saude #nutricao #bemestar",
      "Dicas de relaxamento para reduzir estresse e cuidar de [tema] 😌 #saude #relaxamento #bemestar",
      "Como manter [tema] saudável mesmo com a rotina corrida ⏳ #saude #bemestar #habitos",
      "Alimentos que fortalecem [tema] e aumentam imunidade 🥦 #saude #nutricao #bemestar",
      "Rotina de exercícios leves para proteger [tema] 🤸‍♀️ #saude #fitness #bemestar",
      "Como melhorar qualidade do sono para fortalecer [tema] 😴 #saude #sono #bemestar",
      "Dicas para cuidar da saúde mental e proteger [tema] 🧠 #saude #saudemental #bemestar",
      "Como lidar com a pressão do dia a dia e melhorar [tema] 😌 #saude #stress #bemestar",
      "Benefícios da alimentação saudável diária para [tema] 🥗 #saude #nutricao #bemestar",
      "Como exercícios de respiração ajudam a proteger [tema] 🌬️ #saude #relaxamento #bemestar",
      "Rotina de hábitos diários para manter [tema] em equilíbrio 🌿 #saude #habitos #bemestar",
      "Como manter [tema] saudável durante mudanças sazonais 🍂 #saude #bemestar #prevencao"
    ]
  }
};
