export const TEMPLATES = {
  viagem: {
    post: [
      "Top 5 destinos para explorar [tema] 🏖️ #viagem #destinos #aventura",
      "Como planejar sua viagem para [tema] ✈️ #viagem #planejamento #turismo",
      "Dicas essenciais para viajar para [tema] 🌍 #viagem #dicas #aventura",
      "Experiências únicas em [tema] 🏞️ #viagem #experiencias #natureza",
      "O que fazer em [tema] em um fim de semana 🕒 #viagem #roteiro #turismo",
      "Como economizar viajando para [tema] 💰 #viagem #economia #aventura",
      "Melhores restaurantes em [tema] 🍽️ #viagem #gastronomia #destinos",
      "Dicas de hospedagem em [tema] 🏨 #viagem #hotel #turismo",
      "Passeios imperdíveis em [tema] 🚶‍♂️ #viagem #roteiro #aventura",
      "Como aproveitar ao máximo [tema] em 3 dias 📅 #viagem #roteiro #destinos",
      "Roteiro cultural em [tema] 🎭 #viagem #cultura #turismo",
      "Como fotografar os melhores pontos de [tema] 📸 #viagem #fotografia #destinos",
      "Dicas para viajar sozinho em [tema] 🌍 #viagem #aventura #solo",
      "Como se preparar para uma viagem a [tema] ✈️ #viagem #planejamento #dicas",
      "Aventuras imperdíveis em [tema] 🏞️ #viagem #aventura #natureza",
      "Dicas de transporte em [tema] 🚇 #viagem #mobilidade #destinos",
      "O que visitar em [tema] com crianças 👶 #viagem #familia #turismo",
      "Como conhecer [tema] sem gastar muito 💸 #viagem #economia #aventura",
      "Top atrações turísticas de [tema] 🏛️ #viagem #turismo #roteiro",
      "Dicas de viagem romântica em [tema] 💕 #viagem #romance #destinos",
      "Como explorar [tema] fora do comum 🌿 #viagem #aventura #natureza",
      "Os melhores bares e cafés de [tema] ☕ #viagem #gastronomia #destinos",
      "Roteiro gastronômico em [tema] 🍴 #viagem #gastronomia #turismo",
      "Como aproveitar [tema] em família 👨‍👩‍👧 #viagem #familia #destinos",
      "Dicas para mochileiros em [tema] 🎒 #viagem #mochileiro #aventura",
      "Passeios históricos em [tema] 🏰 #viagem #historia #cultura",
      "Como curtir [tema] em viagens curtas ⏳ #viagem #roteiro #destinos",
      "Dicas de segurança em [tema] 🛡️ #viagem #seguranca #aventura",
      "Como planejar um roteiro econômico em [tema] 💵 #viagem #planejamento #destinos",
      "Aventuras radicais em [tema] 🧗‍♂️ #viagem #aventura #extremo",
      "Top pontos turísticos gratuitos em [tema] 🌟 #viagem #gratuito #destinos",
      "Como explorar a natureza em [tema] 🌿 #viagem #natureza #aventura",
      "Dicas para quem visita [tema] pela primeira vez ✈️ #viagem #primeiraviagem #destinos",
      "Roteiro de 7 dias em [tema] 📅 #viagem #roteiro #aventura",
      "Como viajar com pets para [tema] 🐶 #viagem #pets #destinos",
      "O que levar em uma viagem para [tema] 🎒 #viagem #planejamento #dicas",
      "Melhores trilhas para explorar em [tema] 🥾 #viagem #trilhas #natureza",
      "Como aproveitar o turismo cultural em [tema] 🎭 #viagem #cultura #destinos",
      "Dicas de viagem sustentável em [tema] 🌱 #viagem #sustentavel #aventura",
      "Como curtir [tema] fora de temporada 🏖️ #viagem #lowseason #destinos",
      "Top hotéis boutique em [tema] 🏨 #viagem #hotel #turismo",
      "Passeios imperdíveis para casais em [tema] 💕 #viagem #romance #destinos",
      "Como explorar os mercados locais em [tema] 🛍️ #viagem #cultura #gastronomia",
      "Dicas de viagem para grupos em [tema] 👥 #viagem #grupos #aventura",
      "Como planejar uma viagem de luxo em [tema] 💎 #viagem #luxo #destinos",
      "Roteiro de ecoturismo em [tema] 🌳 #viagem #ecoturismo #natureza",
      "Dicas para viagem gastronômica em [tema] 🍷 #viagem #gastronomia #destinos",
      "Como aproveitar festas e eventos em [tema] 🎉 #viagem #eventos #cultura",
      "Passeios para amantes da história em [tema] 🏛️ #viagem #historia #turismo",
      "Como curtir [tema] com pouco tempo disponível ⏰ #viagem #roteiro #destinos",
      "Roteiro cultural de 3 dias em [tema] 📚 #viagem #cultura #aventura",
      "Dicas de viagem econômica para [tema] 💸 #viagem #economia #destinos",
      "Como explorar praias paradisíacas em [tema] 🏝️ #viagem #praia #aventura",
      "Top atividades ao ar livre em [tema] 🌞 #viagem #natureza #aventura",
      "Como planejar viagem romântica para [tema] 💕 #viagem #romance #destinos",
      "Passeios gratuitos imperdíveis em [tema] 🌟 #viagem #gratuito #turismo",
      "Como se deslocar facilmente em [tema] 🚗 #viagem #mobilidade #destinos",
      "Dicas de viagem de aventura em [tema] 🧗‍♀️ #viagem #aventura #extremo",
      "Como explorar [tema] como um local 🏠 #viagem #cultura #experiencia",
      "Top museus para visitar em [tema] 🖼️ #viagem #museus #cultura",
      "Como planejar roteiro gastronômico em [tema] 🍴 #viagem #gastronomia #destinos",
      "Dicas para viagens de inverno em [tema] ❄️ #viagem #inverno #aventura",
      "Como aproveitar turismo de natureza em [tema] 🌲 #viagem #natureza #destinos",
      "Roteiro de 5 dias em [tema] 📅 #viagem #roteiro #aventura",
      "Como explorar pontos históricos em [tema] 🏛️ #viagem #historia #cultura",
      "Dicas de viagem com orçamento limitado em [tema] 💵 #viagem #economia #destinos",
      "Como curtir atrações turísticas em [tema] com crianças 👶 #viagem #familia #aventura",
      "Top cafés e restaurantes em [tema] ☕ #viagem #gastronomia #destinos",
      "Como planejar viagem de fim de semana em [tema] 📅 #viagem #roteiro #destinos",
      "Passeios culturais imperdíveis em [tema] 🎭 #viagem #cultura #turismo",
      "Dicas de hospedagem econômica em [tema] 🏨 #viagem #economia #destinos",
      "Como aproveitar trilhas e caminhadas em [tema] 🥾 #viagem #trilhas #natureza",
      "Roteiro de aventura radical em [tema] 🧗‍♂️ #viagem #aventura #extremo",
      "Como explorar feiras e mercados locais em [tema] 🛍️ #viagem #cultura #destinos",
      "Dicas para viagem de luxo em [tema] 💎 #viagem #luxo #aventura",
      "Como curtir praias secretas em [tema] 🏝️ #viagem #praia #destinos",
      "Top pontos para fotos incríveis em [tema] 📸 #viagem #fotografia #aventura",
      "Como planejar viagem solo para [tema] 🌍 #viagem #aventura #solo",
      "Passeios românticos imperdíveis em [tema] 💕 #viagem #romance #destinos",
      "Como explorar trilhas naturais em [tema] 🌳 #viagem #natureza #aventura",
      "Dicas de viagem cultural em [tema] 🏛️ #viagem #cultura #destinos",
      "Como planejar roteiro turístico completo em [tema] 📅 #viagem #roteiro #aventura",
      "Top atividades para famílias em [tema] 👨‍👩‍👧 #viagem #familia #destinos",
      "Como aproveitar vida noturna em [tema] 🌙 #viagem #noite #aventura",
      "Roteiro econômico de 3 dias em [tema] 💵 #viagem #economia #destinos",
      "Como explorar parques e reservas naturais em [tema] 🌲 #viagem #natureza #aventura",
      "Dicas para viagem de aventura radical em [tema] 🧗‍♀️ #viagem #aventura #extremo",
      "Como planejar viagem de última hora para [tema] ⏰ #viagem #roteiro #destinos",
      "Passeios de barco e atividades aquáticas em [tema] 🚤 #viagem #praia #aventura",
      "Como explorar atrações gratuitas em [tema] 🌟 #viagem #gratuito #destinos",
      "Dicas para viagens gastronômicas em [tema] 🍷 #viagem #gastronomia #aventura",
      "Como aproveitar cultura local em [tema] 🎭 #viagem #cultura #destinos",
      "Top hotéis e pousadas para visitar em [tema] 🏨 #viagem #hotel #aventura",
      "Como explorar [tema] durante feriados prolongados 📅 #viagem #roteiro #destinos",
      "Roteiro de 7 dias com atrações imperdíveis em [tema] 🏞️ #viagem #roteiro #aventura",
      "Como planejar viagem com crianças em [tema] 👶 #viagem #familia #destinos",
      "Dicas de viagem romântica e inesquecível em [tema] 💕 #viagem #romance #aventura",
      "Como explorar cidades históricas em [tema] 🏰 #viagem #historia #cultura",
      "Passeios ideais para amantes da natureza em [tema] 🌿 #viagem #natureza #aventura",
      "Como planejar roteiro de viagem internacional para [tema] ✈️ #viagem #internacional #destinos",
      "Dicas de viagem econômica para estudantes em [tema] 💸 #viagem #estudantes #aventura"
    ]
  }
};
